- source/ada/lsp-ada_handlers.adb
- testsuite/ada_lsp/0002-shutdown.json
- testsuite/ada_lsp/0003-get_symbols.json
URI can be in two form: `file://absolute_path` and `file:relative_path`.
Process both form correctly. Fix rootURI in tests.
> Fix rootURI processing

- README.md
- gnat/lsp.gpr
- source/ada/lsp-ada_contexts.adb
- source/ada/lsp-ada_contexts.ads
- source/ada/lsp-ada_documents.adb
- source/ada/lsp-ada_documents.ads
- source/ada/lsp-ada_driver.adb
- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-ada_handlers.ads
- source/protocol/lsp-stdio_streams.adb
- source/protocol/lsp-types.ads
- source/protocol/lsp.ads
Depends on https://github.com/AdaCore/langkit/pull/102
and https://github.com/AdaCore/libadalang/pull/164
> First pass of support for completion

- source/ada/lsp-ada_contexts.adb
- source/ada/lsp-ada_contexts.ads
- source/ada/lsp-ada_documents.adb
- source/ada/lsp-ada_documents.ads
- source/ada/lsp-ada_handlers.adb
On Windows we have `file:///C:\PATH`, so we should strip one more slash
to have full path name. Issue #30
> Fix URI parsing with Windows file names.

- Makefile
- source/server/lsp-request_dispatchers.adb
- source/server/lsp-servers.adb
- testsuite/ada_lsp/project_config.json
- testsuite/ada_lsp/project_config/aaa.adb
- testsuite/ada_lsp/project_config/right_project.gpr
- testsuite/ada_lsp/project_config/second.ads
- testsuite/ada_lsp/project_config/third.ads
- testsuite/ada_lsp/project_config/wrong_project.gpr
- testsuite/ada_lsp/project_config_2.json
Add test to find correct .gpr when it's specified by configuration.
> Report error to LSP client on exception as required by LSP.

- Makefile
Removes the dependency on node for users who are not
interested in the vscode integration.
> Use a series of ifs to detect PLATFORM

- source/spawn/spawn-processes__glib_windows.adb
This patch fixes build of Process API (Glib based implementation) on Windows.
When spawn related bindong for Glib was moved to GtkAda repository this file
wasn't fixed. Fix includes some renames to match code in GtkAda that is now
auto generated.
> S327-016 Fix build failure on Windows

- Makefile
- gnat/lsp.gpr
... From "debug/production" to "dev/prod", to match
the settings for the same value in laltools.gpr: the two
meet in the GPS build.
> S329-007 change possible values for BUILD_MODE

- gnat/spawn.gpr
- gnat/spawn_glib.gpr
- source/spawn/spawn-environments-search_in_path__posix.adb
- source/spawn/spawn-environments-search_in_path__windows.adb
- source/spawn/spawn-environments.adb
- source/spawn/spawn-environments.ads
- source/spawn/spawn-windows_api.ads
to search full path of executable. We've considered to let Start
subprogram find full path, but this could be wrong if PATH environment
variable differs in child process environments. So client should find
full path in correct environment with new function Search_Path and pass
full path to Set_Program.
> S125-009 Add Search_Path function to Spawn API

- source/ada/lsp-ada_driver.adb
- source/server/lsp-servers.adb
- source/server/lsp-servers.ads
- testsuite/ada_lsp/0001-start_stop/0001-start_stop.json
Introduce a separate task for the actual processing, synchronized
to the main task via a queue of requests. This allows the main
task to never be blocking on input when libadalang is performing
an expensive computation. This will also be used to implement
a basic support for cancelling requests.
Also process the output in a separate task.
> S328-046 Introduce asynchronous processing

- source/ada/lsp-ada_handlers.adb
- testsuite/ada_lsp/spec_from_body/spec_from_body.json
Rewrite 'textDocument/definition' request:
* if you click on identifier that not a defining_name (not a subprogram spec or body)
then return just single location of subprogram spec
* if you click on defining_name of subprogram spec then return only single location of subprogram body
* if you click on defining_name of subprogram body then return only single location of subprogram spec
> S405-010 Process defining_name in a different way

- gnat/lsp.gpr
- gnat/lsp_server.gpr
- gnat/tester.gpr
- source/uri/uris.adb
- source/uri/uris.ads
This is very convenient for clients to be able to convert from
file names to URIs without having to reimplement their routines.
Also change the test for checking that file names are absolute to
one that works with final directory separators.
> S506-022 make the URIs package accessible to clients

- source/uri/uris.adb
The internal function Add_All_Paths doesn't expect
a directory which ends in a separator.
> S506-022 Fix URIs.Conversions.From_File for full paths

- source/ada/lsp-ada_contexts.adb
- source/ada/lsp-ada_driver.adb
- source/server/lsp-servers.adb
Make sure any exception in finalization is fatal, preventing an
infinite loop on trying to exit.
Prevent any exception in task processing from quitting the task
main loops.
> S506-022 Add defensive code

- source/server/lsp-servers.adb
- source/tester/tester-tests.adb
- testsuite/ada_lsp/S510-020.exceptions_reporting/test.json
- testsuite/ada_lsp/S510-020.exceptions_reporting/test.yaml
When decoding of requests or processing of requests generate
exceptions, send a response with a detailed message.
Add an automated test. To support the writing of the test,
add a special case that allows writing `"<ANY>"` in the test
driver to match any string.
> S510-020 Make sure to send error responses when exceptions occur

- source/ada/lsp-ada_handlers.adb
In case of enum literals, we want to display the declaration of the whole enumeration type instead.
> S329-011: Add special case for enum literals

- source/ada/lsp-ada_documents.adb
- source/protocol/lsp-messages.adb
- source/protocol/lsp-types.adb
- source/protocol/lsp-types.ads
Introduce a new function for string conversions
that avoids stack allocation, and use this in the
case of a giant string.
> S516-036 avoid allocating large strings on the stack

- README.md
- source/ada/lsp-ada_contexts.adb
- source/ada/lsp-ada_contexts.ads
- source/ada/lsp-ada_handlers.adb
- testsuite/ada_lsp/publish_diag/publish_diag_disabled.json
And document this setting, along with defaultCharset,
in the README.md.
Add a test for deactivation of diagnostics.
> S528-016 Add a setting to deactivate diagnostics

- source/protocol/lsp-messages.adb
- testsuite/ada_lsp/0002-shutdown/0002-shutdown.json
- testsuite/ada_lsp/0003-get_symbols/0003-get_symbols.json
- testsuite/ada_lsp/S516-013.no_file/no_file.json
- testsuite/ada_lsp/def_name/def_name.json
- testsuite/ada_lsp/def_name/uri_with_slash.json
- testsuite/ada_lsp/find_all_refs/find_all_refs.json
- testsuite/ada_lsp/find_all_refs_subp/find_all_refs_subp.json
- testsuite/ada_lsp/no_root/no_root.json
- testsuite/ada_lsp/no_root/uri_with_slash.json
- testsuite/ada_lsp/project_config/project_config.json
- testsuite/ada_lsp/project_config/project_config_2.json
- testsuite/ada_lsp/project_search/project_search.json
- testsuite/ada_lsp/publish_diag/diag_on_open.json
- testsuite/ada_lsp/publish_diag/publish_diag.json
- testsuite/ada_lsp/publish_diag/publish_diag_disabled.json
- testsuite/ada_lsp/publish_diag/test.yaml
- testsuite/ada_lsp/spec_from_body/spec_from_body.json
According to JSON-RPC documentation this member is required on success.
Also add "result" properties to existing tests.
> S603-002 Add "result" property to Shutdown response.

- Makefile
- source/ada/lsp-ada_driver.adb
If there is a '.gnatdebug' file in the directory where the ALS
is launched, use this as traces configuration file. Useful
essentially for developers.
Modify the test driver so that each test is run in its
directory, in case we need to add .gnatdebug files local
to specific tests.
> Add support for local traces

- source/protocol/lsp-messages.adb
- source/server/lsp-servers.adb
- source/tester/tester-tests.adb
- testsuite/ada_lsp/README.md
- testsuite/ada_lsp/S510-020.exceptions_reporting/test.json
* lsp-messages.adb: Check Is_Error explicitly
* lsp-servers.adb: Move exception handlers into
Process_Message_From_Stream. Send error responses only on
requests. Drop reading result from client's responses for now.
Add an extra enclosing block to separate decoding exceptions
and report errors with InvalidParams code.
* tester-tests.adb: Add a special value "<ABSENT>" to allow
tester check extra properties in server reponses.
* testsuite/ada_lsp/README.md: improve tester documentation.
* S510-020.exceptions_reporting/test.json: Fix testcase.
> S607-007 Don't send "result" on errors

- doc/README.md
- doc/called_by.md
- scripts/generate.py
- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-ada_handlers.ads
- source/ada/lsp-lal_utils.adb
- source/ada/lsp-lal_utils.ads
- source/protocol/generated/lsp-messages-requests.adb
- source/protocol/generated/lsp-messages-requests.ads
- source/protocol/lsp-messages.adb
- source/protocol/lsp-messages.ads
- testsuite/ada_lsp/called_by/called_by.json
- testsuite/ada_lsp/called_by/main.adb
- testsuite/ada_lsp/called_by/p.adb
- testsuite/ada_lsp/called_by/p.ads
- testsuite/ada_lsp/called_by/p.gpr
Introduce a custom request "textDocument/ALS_called_by".
Add a subprogram in LSP.LAL_Utils to implement the functionality,
add support for marshalling/unmarshalling the response to the
JSON stream, and add support for serving this request in the LSP
server.
Move the utility function Find_All_References to LSP.LAL_Utils.
Add a test for the 'called_by' functionality.
> S603-029  implement "is called by" as a custom request

- source/uri/uris.adb
The behavior of Ada.Directories.Containing_Directory has
changed slightly. The code that added support for this was
not taking into account the situation on Windows; this is
now done.
Clarify the corresponding comment to say that this is an
API change in Ada.Directories, not in GNAT per se.
> S624-027 Add adaptation for the new API in Ada.Directories

- doc/reference_kinds.md
- source/ada/lsp-ada_documents.adb
- source/ada/lsp-ada_handlers.adb
- source/protocol/lsp-messages.adb
- source/protocol/lsp-messages.ads
- testsuite/ada_lsp/find_all_refs/find_all_refs.json
- testsuite/ada_lsp/find_all_refs_kinds/aaa.adb
- testsuite/ada_lsp/find_all_refs_kinds/find_all_refs_kinds.json
- testsuite/ada_lsp/find_all_refs_kinds/p.gpr
- testsuite/ada_lsp/find_all_refs_kinds/test.yaml
- testsuite/ada_lsp/find_all_refs_subp/find_all_refs_subp.json
Add an extension to LSP to return reference kinds in
responses to textDocument/references.
> S329-013 Send alsKind in textDocument/references responses.

- source/protocol/lsp-messages.adb
- testsuite/ada_lsp/rename/rename.json
Before this patch ALS doesn't send 'result:' property at all.
> S625-031 Fix an empty response to textDocument/rename

- source/ada/lsp-lal_utils.adb
- source/client/lsp-raw_clients.adb
- source/protocol/lsp-messages.adb
- source/server/lsp-servers.adb
- source/spawn/spawn-environments-initialize_default__windows.adb
- source/spawn/spawn-environments-search_in_path__windows.adb
- source/spawn/spawn-processes-windows.adb
- source/tester/tester-tests.adb
- source/uri/uris.adb
As per AdaCore's coding style, and to avoid logic errors: programmers
usually rely on Y not to be evaluated when X is False in (X AND Y),
likewise for OR operations.
> Consistently use short-circuit boolean operators

- integration/travis/Dockerfile
- source/ada/lsp-ada_documents.adb
- source/ada/lsp-ada_handlers.adb
In the hope to improve the response time for user requests,
populate the lexical env for units when the files are being
opened.
Send 'log' traces around the call to Load_Document, for
development purposes.
> S624-042 Pre-populate the lexical env for units

- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-lal_utils.adb
- source/ada/lsp-lal_utils.ads
We now send an LSP message when using the libadalang's imprecise
fallback mechanism: an info message is send for textDocument/definition
and a simple log message is sent in other cases.
> S610-031: send messages when using Imprecise_Fallback

- source/server/lsp-servers.adb
- source/server/lsp-servers.ads
Now "exit" notification stops Input_Task and it signals the server
to terminate.
> S705-018 Don't use OS_Exit to terminate the process

- source/uri/uris.adb
Prevent storing an uninitialized variable. Detected by valgrind.
> Fix logic in URI parsing

- source/ada/lsp-ada_documents.adb
- source/ada/lsp-ada_documents.ads
Analysis Units are not meant to be stored. Instead, store
the latest known version of the buffer, encoded in UTF-8, and
compute the Analysis Unit on demand.
> S728-002 Do not store an Analysis_Unit in the Document

- README.md
- scripts/json_transformations.py
- scripts/replay.py
- scripts/traces_to_test.py
The script "traces_to_test.py" is now better at generating
test cases with "waits" corresponding to the "sends" and
requiring much fewer modifications by hand.
> Improvements to the development scripts

- source/ada/lsp-ada_contexts.adb
- source/ada/lsp-ada_contexts.ads
- source/ada/lsp-ada_driver.adb
- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-ada_handlers.ads
- testsuite/ada_lsp/non_project_files/non_prj/p2.adb
- testsuite/ada_lsp/non_project_files/non_project_files.json
- testsuite/ada_lsp/non_project_files/p.adb
- testsuite/ada_lsp/non_project_files/p.ads
- testsuite/ada_lsp/non_project_files/test.yaml
This is a first step for supporting multiple projects: add support
for more than one Context, and organise the requests so that
they either get the results from all contexts and aggregate
them, or only query the results from the appropriate context.
At the moment, there is only one project loaded, and we have
added one context to hold all files that are not associated
to a project.
Move the diagnostics preference from the Context to the
Message_Handler.
> S815-010 S709-013 Initial code for multi-project support

- source/ada/lsp-lal_utils.adb
- source/ada/lsp-lal_utils.ads
- testsuite/ada_lsp/JB24-033.xrefs.no_refs_for_non_loaded_projects/test.json
to prevent "goto definition" jump to the body.
> S703-028 Make Resolve_Name return canonical part of defining name

- source/ada/lsp-ada_contexts.adb
- source/ada/lsp-ada_contexts.ads
- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-ada_handlers.ads
- source/ada/lsp-ada_unit_providers.adb
- source/ada/lsp-ada_unit_providers.ads
- testsuite/ada_lsp/aggregate.simple/agg.gpr
- testsuite/ada_lsp/aggregate.simple/common/common.gpr
- testsuite/ada_lsp/aggregate.simple/common/common_pack.ads
- testsuite/ada_lsp/aggregate.simple/p/main.adb
- testsuite/ada_lsp/aggregate.simple/p/p.gpr
- testsuite/ada_lsp/aggregate.simple/q/main.adb
- testsuite/ada_lsp/aggregate.simple/q/q.gpr
- testsuite/ada_lsp/aggregate.simple/test.json
- testsuite/ada_lsp/aggregate.simple/test.yaml
Add support for aggregate projects. To do this, move
project loading from the Context to the Message_Handler: the
Message_Handler is responsible for creating one Context per
project hierarchy within the aggregate project.
Add a first test to check the result of finding all references
in a simple aggregate project tree.
> S910-023 Add support for aggregate projects

- source/ada/lsp-ada_handlers.adb
- testsuite/ada_lsp/README.md
Load the project at one of two opportunities:
- in reaction to didChangeConfiguration
- if this didn't happen, when opening a source editor
This makes sure we don't load a same project twice, and prevents
emitting spurious errors in reaction to initialize.
> S911-041 Rationalize project loading

- doc/called_by.md
- doc/debug.md
- scripts/generate.py
- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-ada_handlers.ads
- source/protocol/generated/lsp-messages-server_requests.adb
- source/protocol/generated/lsp-messages-server_requests.ads
- source/protocol/generated/lsp-server_request_receivers.ads
- source/protocol/lsp-messages-server_responses.adb
- source/protocol/lsp-messages-server_responses.ads
- source/protocol/lsp-messages.adb
- source/protocol/lsp-messages.ads
- source/protocol/lsp-server_response_senders.ads
- source/server/generated/lsp-server_request_handlers.ads
- source/server/generated/lsp-servers-decode_request.adb
- source/server/generated/lsp-servers-handle_request.adb
- source/server/lsp-message_loggers.adb
- source/server/lsp-message_loggers.ads
- source/server/lsp-servers.adb
- source/server/lsp-servers.ads
- testsuite/ada_lsp/cancel/cancel.json
- testsuite/ada_lsp/cancel/test.yaml
New auxilary request `$/alsDebug` was added to suspend request
execution until message input queue has given number of messages.
> Add testcase for `$/cancelRequest`

- source/ada/lsp-ada_contexts.adb
- source/ada/lsp-ada_contexts.ads
- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-lal_utils.adb
- source/ada/lsp-lal_utils.ads
Improve the user experience around "find all references" and
"called by" operations:
- first attempt the operation in precise mode, falling back
on imprecise mode in case of Property_Error
- even in imprecise mode, catch Property_Error and send empty
results
- send a message to the user when imprecise results are being
returned
- in the case of 'rename', abort the rename operation if the results
are not precise.
> S918-055 improve exception handling and error reporting

- source/ada/lsp-ada_contexts.adb
- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-common.adb
- source/ada/lsp-common.ads
- source/ada/lsp-lal_utils.adb
- source/ada/lsp-lal_utils.ads
We're often expecting this exception and catching it so that
the user does not see it: capture these in the traces, to ease
debugging and investigation.
> S925-011 log all "Property_Error" exceptions to traces

- source/ada/lsp-ada_handlers.adb
- testsuite/ada_lsp/called_by_dispatching/child.ads
- testsuite/ada_lsp/called_by_dispatching/main.adb
- testsuite/ada_lsp/called_by_dispatching/p.gpr
- testsuite/ada_lsp/called_by_dispatching/root.ads
- testsuite/ada_lsp/called_by_dispatching/test.json
- testsuite/ada_lsp/called_by_dispatching/test.yaml
This allows the client to differentiate calls that are made
through dispatching, for instance.
Add test.
> S822-037 inform alsReferenceKind in the result of alsCalledBy

- README.md
I have a pending PR in https://github.com/emacs-lsp/lsp-mode/pull/1079
to integrate natively ada_language_server with emacs. This PR provides the necessary documentation to configure the server at the project level.
> Document emacs integration in ada_language_server

- source/server/lsp-servers.adb
- testsuite/ada_lsp/cancel/cancel.json
The "Cancel Test" is buggy because it waits to "canceled" response too late,
we should wit for it in cancel notification directly, otherwise test could
miss it.
On the other side implemetation of Input_Queue_Length is incorrect, because
it doesn't take into account the look ahead buffer.
> SA09-029 Fix non-determinism in cancelRequest test.

- README.md
- integration/travis/deploy.sh
- integration/vscode/ada/package.json
As I introduced versioning for ALS community release I accidentally broke
vscode package. Also binary archives for master branch changed their names.
I fix this in patch. So, for master branch:
* vsix extension now has version 20.0.999 (that correspond to GPS 20.0w)
* its file name is ada-20.0.999.vsix
* ALS for Linux is linux-latest.tar.gz
* ALS for Windows is win32-latest.zip
* ALS for Darwin is darwin-latest.tar.gz
> SA07-038 Fix version and file names.

- source/ada/lsp-ada_handlers.adb
Some clients (VScode is an example) might display these messages
to the user a bit too intrusively for the intended purpose.
> SA09-029 Suppress noisy "loading"/"done loading" messages

- Makefile
This is much faster for developers.
> If e3 is available, use the e3-based testsuite driver

- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-lal_utils.adb
- source/ada/lsp-lal_utils.ads
- testsuite/ada_lsp/SA11-040.definition.fallback/p.adb
- testsuite/ada_lsp/SA11-040.definition.fallback/p.ads
- testsuite/ada_lsp/SA11-040.definition.fallback/p.gpr
- testsuite/ada_lsp/SA11-040.definition.fallback/test.json
- testsuite/ada_lsp/SA11-040.definition.fallback/test.yaml
This mechanism is based on a naive heuristics and is meant
for the language server to be able to provide navigation from
a subprogram spec to the body (and vice versa) after modifying
the profile in one of the parts but not the other.
Add a test.
> SA11-040 Add a fallback mechanism for 'definition'

- integration/vscode/ada/gpr-language-configuration.json
- integration/vscode/ada/gpr-snippets.json
- integration/vscode/ada/language-configuration.json
- integration/vscode/ada/package.json
- integration/vscode/ada/syntaxes/gpr.tmLanguage.json
Hello,
I'm here again with a new PR to add new facility to the Visual Studio code extension.
This time is the syntax highlighting support for .gpr project files.
Hope this was also in your plans to add support for it.
Would it be possible to integrate it an push a new version of the Visual Studio Extension onto its marketplace ?
Thanks a lot.
Kind regard,
Denis Gautherot.
> [enh] Add gpr language support for GNAT Project Manager

- source/ada/lsp-ada_documents.adb
- testsuite/ada_lsp/incorrect_fallback/incorrect_fallback.json
- testsuite/ada_lsp/publish_diag/publish_diag.json
Diagnostics of the form "Cannot parse <..>" are not
generally interesting to the end user: filter them out
from the list of diagnostics being reported.
> SB15-028 Filter out some diagnostics

- README.md
- source/ada/lsp-ada_driver.adb
- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-ada_handlers.ads
- source/server/generated/lsp-server_request_handlers.ads
- source/server/lsp-server_backends.ads
- source/server/lsp-servers.adb
- source/server/lsp-servers.ads
- testsuite/ada_lsp/rename.not_up_to_date/test.json
Make the indexing take place "in the background".
To do this,
* make the index subprogram stop itself when there is work on the queue
* add an interface that allows the server to do operations after each
request/operation, and use this to relaunch an indexing request
> SB18-028 Allow requests processing during Indexing

- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-ada_handlers.ads
- source/ada/lsp-lal_utils.adb
- source/ada/lsp-lal_utils.ads
- testsuite/ada_lsp/SA22-029.rename_in_comments/hello.gpr
- testsuite/ada_lsp/SA22-029.rename_in_comments/main.adb
- testsuite/ada_lsp/SA22-029.rename_in_comments/p.adb
- testsuite/ada_lsp/SA22-029.rename_in_comments/p.ads
- testsuite/ada_lsp/SA22-029.rename_in_comments/p1.adb
- testsuite/ada_lsp/SA22-029.rename_in_comments/p1.ads
- testsuite/ada_lsp/SA22-029.rename_in_comments/test.json
- testsuite/ada_lsp/SA22-029.rename_in_comments/test.yaml
Added:
- renameInComments configuration option to control whether
process also comments when renaming or not
- process comments and includes locations in response when
comment should be changed
- new test
> SA22-029 Rename also in comments

- source/ada/lsp-ada_contexts.adb
- source/ada/lsp-ada_contexts.ads
- source/ada/lsp-ada_handlers.adb
- testsuite/ada_lsp/definition_and_overridings/class_definition.adb
- testsuite/ada_lsp/definition_and_overridings/class_definition.ads
- testsuite/ada_lsp/definition_and_overridings/class_definition.subclass.adb
- testsuite/ada_lsp/definition_and_overridings/class_definition.subclass.ads
- testsuite/ada_lsp/definition_and_overridings/default.gpr
- testsuite/ada_lsp/definition_and_overridings/gb.adb
- testsuite/ada_lsp/definition_and_overridings/test.json
- testsuite/ada_lsp/definition_and_overridings/test.yaml
- testsuite/ada_lsp/definition_and_overridings/user.adb
- testsuite/ada_lsp/definition_and_overridings/user.ads
We now propose the overriding subprograms declarations when responding
to textDocument/definition requests, if any.
This allows for instance to get the declarations of all the
implementations of a given subprogram when right-clicking on
a dispatching call or ab abstract suprogram declaration.
An automatic test has also been added.
> S813-025: Get overriding subprograms on textDocument/definition

- doc/README.md
Use the same kind of brackets that is used for "Reference kinds" feature description
> Fix brackets to make hyperlink work

- README.md
- doc/HACKING.md
- scripts/traces_to_test.py
Create a doc/HACKING.md, move some data from the global README.md
to there.
Slight improvement to traces_to_test.py.
> SB22-006 Document the writing of tests

- source/ada/lsp-ada_handlers.adb
The pointers to the contexts were never released, and as a result
the Analysis_Context was never released.
> Fix memory leak when reloading projects

- source/tester/tester-tests.adb
- source/tester/tester-tests.ads
With the introduction of progress reports, the "last message from
server" is no longer helpful: send the full report to the testsuite
output instead.
> Make testsuite output more verbose

- source/ada/lsp-ada_contexts.adb
- source/ada/lsp-ada_contexts.ads
- source/ada/lsp-ada_documents.adb
- source/ada/lsp-ada_documents.ads
- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-ada_handlers.ads
- testsuite/ada_lsp/aggregate.references_after_update/agg.gpr
- testsuite/ada_lsp/aggregate.references_after_update/common/common.gpr
- testsuite/ada_lsp/aggregate.references_after_update/common/common_pack.ads
- testsuite/ada_lsp/aggregate.references_after_update/p/main.adb
- testsuite/ada_lsp/aggregate.references_after_update/p/p.gpr
- testsuite/ada_lsp/aggregate.references_after_update/q/main.adb
- testsuite/ada_lsp/aggregate.references_after_update/q/q.gpr
- testsuite/ada_lsp/aggregate.references_after_update/test.json
- testsuite/ada_lsp/aggregate.references_after_update/test.yaml
Documents should not belong to specific contexts. For instance, a
document might represent an Ada source which is common to several
project contexts. Following this, a document should not own its
Analysis_Unit, the Analysis_Unit is valid only for a specific context.
Refactor the code in light of this: the documents are now held by
the Message_Handler.
Add a test to check that references for an entity that's common to several
project works after editing the document.
> SC06-075 Separate Documents from Contexts

- source/tester/tester-tests.adb
- testsuite/drivers/basic.py
- testsuite/run_valgrind.sh
- testsuite/testsuite.py
Add a mode to run the testsuite under valgrind.
To do this, the command line to run the language server
must be modifiable: no longer read it from the .json files,
but read it from the environment directly.
> SC06-071 Add a valgrind mode to the testsuite

- Makefile
The OS env variable is defined only on windows, so to use it on darwin and
linux we need to define it explicitly in the makefile.
> Enable builds of ALS on Darwin.

- source/ada/lsp-lal_utils.adb
- testsuite/ada_lsp/SC16-095.fallback_when_no_body/p.gpr
- testsuite/ada_lsp/SC16-095.fallback_when_no_body/pack.adb
- testsuite/ada_lsp/SC16-095.fallback_when_no_body/pack.ads
- testsuite/ada_lsp/SC16-095.fallback_when_no_body/test.json
- testsuite/ada_lsp/SC16-095.fallback_when_no_body/test.yaml
Decls that are 'is null' procedures, abstract subprograms, or
expression functions should not allow a body: prevent the manual
fallback mechanism for finding one.
> SC16-095 Prevent fallback navigation on decls that don't allow a body

- source/ada/lsp-ada_contexts.adb
- source/ada/lsp-ada_contexts.ads
- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-lal_utils.adb
- source/ada/lsp-lal_utils.ads
- testsuite/ada_lsp/rename.tagged_type_primitives/children.adb
- testsuite/ada_lsp/rename.tagged_type_primitives/children.ads
- testsuite/ada_lsp/rename.tagged_type_primitives/default.gpr
- testsuite/ada_lsp/rename.tagged_type_primitives/great_children.adb
- testsuite/ada_lsp/rename.tagged_type_primitives/great_children.ads
- testsuite/ada_lsp/rename.tagged_type_primitives/main.adb
- testsuite/ada_lsp/rename.tagged_type_primitives/parents.ads
- testsuite/ada_lsp/rename.tagged_type_primitives/test.json
- testsuite/ada_lsp/rename.tagged_type_primitives/test.yaml
The textDocument/rename request handler now also renames the overriding
and base primitives when dealing with tagged type primitives.
> SA18-022: Allow renaming overriding/base primitives

- source/ada/lsp-ada_handlers.adb
- testsuite/ada_lsp/type_definition.aggregate/agg.gpr
- testsuite/ada_lsp/type_definition.aggregate/common/common_pack.ads
- testsuite/ada_lsp/type_definition.aggregate/p-loc.xml
- testsuite/ada_lsp/type_definition.aggregate/p/main.adb
- testsuite/ada_lsp/type_definition.aggregate/p/p.gpr
- testsuite/ada_lsp/type_definition.aggregate/p/truc.ads
- testsuite/ada_lsp/type_definition.aggregate/pack.adb
- testsuite/ada_lsp/type_definition.aggregate/pack.ads
- testsuite/ada_lsp/type_definition.aggregate/q/main.adb
- testsuite/ada_lsp/type_definition.aggregate/q/q.gpr
- testsuite/ada_lsp/type_definition.aggregate/q/truc.ads
- testsuite/ada_lsp/type_definition.aggregate/test.json
- testsuite/ada_lsp/type_definition.aggregate/test.yaml
- testsuite/ada_lsp/type_definition/type_definition.json
This was not working in the context of aggregate projects,
and was not working when requested on the definition of the
type itself, only on an use of the type.
Add a test that covers both cases.
> SC19-050 Fix textDocument/typeDefinition

- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-lal_utils.adb
- source/ada/lsp-lal_utils.ads
- testsuite/ada_lsp/implementation.overridings/p.gpr
- testsuite/ada_lsp/implementation.overridings/pack.adb
- testsuite/ada_lsp/implementation.overridings/pack.ads
- testsuite/ada_lsp/implementation.overridings/test.json
- testsuite/ada_lsp/implementation.overridings/test.yaml
Similarly to 'declaration', this requests now lists the implementations
of parent and child definitions of the subprogram.
Also slightly improve the behavior of 'implementation': return the
declaration if it's an "is null" procedure or an expression function.
Fix a bug that returned no results for subprograms that didn't have
a declaration.
Add a test.
> SC20-022 'implementation' now returns bodies for parent/child methods

- source/ada/lsp-ada_handlers.adb
- testsuite/ada_lsp/implementation.overridings/test.json
Adjustment to the previous change: do not return abstract
definitions in the list of implementations.
Cleanup the test, removing the queries for textDocument/hover
that don't belong to this case.
> SC20-022 'implementation': do not list abstract definitions

- README.md
- integration/travis/deploy.sh
- integration/vscode/ada/package.json
Populate CHANGELOG.md with commit messages of release tags.
Minor fixes in README.md and package.json.
> Generate CHANGELOG.md on deploy vscode extension

- integration/vscode/ada/package.json
It was accidentally broken in the previous commit.
> Fix JSON syntax in package.json

- source/ada/lsp-ada_documents.adb
- source/ada/lsp-ada_documents.ads
- source/protocol/lsp-messages-server_responses.ads
- source/server/lsp-message_loggers.adb
In the newest version of the protocol we now have the possibility
to return either a flat list of symbols or a tree of symbols.
> SA21-029: fix textDocument/symbols response type

- source/ada/lsp-ada_documents.adb
For constructs like
when Ada.Text_IO.Data_Error =>
null;
Libadalang create a null defining name. Skip such names
when creating a document symbol hierarchy.
> SC27-004 Avoid Constraint_Error on a null defining name.

- source/ada/lsp-ada_contexts.adb
- testsuite/ada_lsp/rename.primitive_parameters/default.gpr
- testsuite/ada_lsp/rename.primitive_parameters/src/children.adb
- testsuite/ada_lsp/rename.primitive_parameters/src/children.ads
- testsuite/ada_lsp/rename.primitive_parameters/src/great_children.adb
- testsuite/ada_lsp/rename.primitive_parameters/src/great_children.ads
- testsuite/ada_lsp/rename.primitive_parameters/src/main.adb
- testsuite/ada_lsp/rename.primitive_parameters/src/parents.ads
- testsuite/ada_lsp/rename.primitive_parameters/test.json
- testsuite/ada_lsp/rename.primitive_parameters/test.yaml
When renaming a parameter of a tagged type primitive, we now
also rename this parameter in all the base and overriding
subprograms.
> SA18-022: Rename parameters in the whole hierarchy

- testsuite/testsuite.py
Purely for developer convenience when investigating memory
issues.
> (minor) Add a commented-out valgrind parameter

- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-lal_utils.adb
- source/ada/lsp-lal_utils.ads
- testsuite/ada_lsp/D301-004.xrefs.generics/test.json
- testsuite/ada_lsp/aggregate.references_after_update/test.json
- testsuite/ada_lsp/aggregate.simple/test.json
- testsuite/ada_lsp/definition_parents/test.json
- testsuite/ada_lsp/implementation.overridings/test.json
When returning a list of locations, we were checking at each insertion
whether the location was already present in the results. This has
a cost of O(n^2)
Instead, append the locations, and sort/remove duplicates only at
the end, changing the cost to O(n*log(n)).
Sort the results by file then location; when sorting files in the
same directory, use a slightly more logical sort than an alphabetic
sort, returning locations in the .ads before the .adb, and the parent
package before the child packages.
> SB25-033 Remove performance bottleneck

- source/protocol/lsp-generic_optional.adb
Corner case is an empty JSON object. Before this patch it's
read as an absent value.
> SA17-041 Fix reading of optional values.

- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-ada_handlers.ads
- source/server/lsp-server_backends.ads
- source/server/lsp-servers.adb
- source/server/lsp-servers.ads
to simplify Server interface, avoid task checking and decouple
Ada_Handler from Server a little more.
> SB18-028 Minor refactoring. Hide Has_Pending_Work from Server API

- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-ada_handlers.ads
- testsuite/ada_lsp/non_project_files/non_prj/p2.adb
- testsuite/ada_lsp/non_project_files/non_project_files.json
In the case that no project is specified, use an implicit
project which covers the subdirectories as well. This is slightly
friendlier for VScode users who don't have a .gpr at the root
of a hierarchy. Adapt test baselines in light of this.
Now that documents are owned by the handler, there is no longer
the need for a "projectless" context. Clean up the code in light
of this.
> T123-038 Improve project handling, and clean code up

- source/ada/lsp-ada_contexts.adb
- source/ada/lsp-common.ads
- testsuite/ada_lsp/declaration.overridings/p.gpr
- testsuite/ada_lsp/declaration.overridings/pack.adb
- testsuite/ada_lsp/declaration.overridings/pack.ads
- testsuite/ada_lsp/declaration.overridings/test.json
- testsuite/ada_lsp/declaration.overridings/test.yaml
To mimic what we are already doing for textDocument/definition.
> T131-020: Add child/parent kinds for textDocument/declaration

- integration/vscode/ada/syntaxes/ada.tmLanguage.json
> Fix identifier's highlight in vscode extension.

- source/ada/lsp-ada_context_sets.adb
- source/ada/lsp-ada_context_sets.ads
- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-ada_handlers.ads
The runtime files should be considered when considering
which contexts are appropriate for a given URI. Do this
by maintain a cache of runtime files.
This fixes requests such as 'called_by' when initiated from
the runtime.
NOTE: it's not possible to add a test in this repository in the
current architecture, since the location of runtime files is a
moving target. I will propose a test as part of GNAT Studio.
> SB05-051 Consider runtime files as part of project files

- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-ada_handlers.ads
When the language server is loading an implicit project,
check whenever a new file is open: if it's in a directory that's
outside of the project, add it and reload the project.
> T130-026 When the project is implicit, load dirs on demand

- source/ada/lsp-ada_contexts.adb
We were multiplying by 2 in case there is a body for the
base/derived declaration, but in fact we are also adding
the end label when found, so we should multiply the resulting
array size by 3.
> T211-042: Increase the references array size for hierarchies

- source/ada/lsp-ada_handlers.adb
Without a separator the message looks like:
> Unable to load project file: /tmp/sorting.gprsorting.gpr:1:01: "project" expected
Also drop usage of a depricated package (ASCII).
> Fix error message to display when ALS is unable to load a project

- testsuite/leaks.supp
- testsuite/testsuite.py
As discussed with the GPR team, the leak is inconsequential.
Increase the timeout multiplier in an effort to stabilize the
nightly runs.
> T114-020 add a valgrind exception, and increase timeout multiplier

- integration/vscode/ada/syntaxes/ada.tmLanguage.json
- integration/vscode/ada/syntaxes/ali.tmLanguage.json
- integration/vscode/ada/syntaxes/gpr.tmLanguage.json
I've flattened the syntax files for ALI/GPR completely. The Ada syntax files have been partially flattened, with the remaining components being easier to tackle through a bottom-up rewrite of those parts.
> Flatten syntax files

- integration/vscode/ada/syntaxes/ada.tmLanguage.json
Flattened values and updated them to the better regex I gave you guys before. They've been acutely classified so supporting themes can do this:
While falling back to this:
> Flattened and improved value highlighting

- integration/vscode/ada/syntaxes/ada.tmLanguage.json
Certain themes, namely the Microsoft Light+/Dark+ themes, highlight `storage.type` the same as `keyword`, which is appropriate for C/C++/C#, but not most other languages. This winds up being confusing with Ada. By using `entity.name.type`, all the built in themes highlight types distinctly.
> Fixes type names for certain themes

- testsuite/drivers/basic.py
Apply the multiplying factor to the executable timeout, capped
at a maximum.
> Increase the timeout in case of valgrind runs

- integration/vscode/ada/syntaxes/ada.tmLanguage.json
Split `exception` into `exception_declaration`, `raise_statement`, and `raise_expression`.
Now additionally supports raise statements with a `with <<expression>>`. Added a stub for `expression`, but it doesn't have anything yet. I can translate most EBNF to VS Code grammar, but expressions are an exception to that.
> FlattenException

- integration/vscode/ada/syntaxes/ada.tmLanguage.json
Flattened `aspect` into `aspect_mark`, `aspect_specification`, and `aspect_definition`. Entirely uses begin-end ranges, so it should be far more tolerant to line breaks.
> Flattened aspect

- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-lal_utils.adb
- source/ada/lsp-lal_utils.ads
- testsuite/ada_lsp/rename/main.adb
- testsuite/ada_lsp/rename/rename.json
For example:
rename 'A' to 'B' but not 'A_letter' to 'B_Letter'
> T313-025 Rename only whole words in comments

- source/spawn/pipe2.c
- source/spawn/posix_const.c
where there is no O_CLOEXEC nor pipe2. This fix is to avoid
compilation error there.
> T318-072 We still compile ALS on RHES 5

- Makefile
- doc/HACKING.md
- source/ada/lsp-ada_driver.adb
- source/memory/lsp-memory_statistics.adb
- source/memory/lsp-memory_statistics.ads
- source/memory/s-memory.adb
- source/server/lsp-servers.adb
when the DEBUG.ADA_MEMORY trace is enabled, we now monitor the
memory usage consumption and dump it in the logs.
This allows to identify which parts of the program are the
biggest memory usage consumers.
The stacktrace addresses are resolved using GNAT.Symbolic.Traceback
because we link the ALS with relocatable libraries.
> T306-021: Add memory usage monitor based on GNATCOLL.Memory

- integration/vscode/ada/package.json
- source/ada/lsp-ada_handlers.adb
- source/protocol/lsp-client_request_receivers.ads
- source/protocol/lsp-messages-client_requests.adb
- source/protocol/lsp-messages-client_requests.ads
- source/protocol/lsp-messages.adb
- source/protocol/lsp-messages.ads
- source/server/lsp-message_loggers.adb
- source/server/lsp-message_loggers.ads
- source/server/lsp-servers.adb
- source/server/lsp-servers.ads
- testsuite/ada_lsp/indexing_progress/test.json
before sending work progress report. This enables progress indicator
in vscode.
> T311-013 Execute window/workDoneProgress/create request

- source/ada/lsp-ada_context_sets.adb
- source/ada/lsp-ada_context_sets.ads
- source/ada/lsp-ada_handlers.adb
- testsuite/ada_lsp/invalid_project/foo.ads
- testsuite/ada_lsp/invalid_project/invalid.gpr
- testsuite/ada_lsp/invalid_project/main.adb
- testsuite/ada_lsp/invalid_project/test.json
- testsuite/ada_lsp/invalid_project/test.yaml
When the language server is given a project that does not load,
it should fall back on the implicit project.
Clarify the documentation and behavior of Get_Best_Context.
> T330-041 Fix behavior when encountering an invalid project

- source/ada/lsp-ada_documents.adb
- source/ada/lsp-ada_documents.ads
- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-ada_handlers.ads
- source/tester/tester-macros.adb
- testsuite/ada_lsp/completion.subp_parameters/default.gpr
- testsuite/ada_lsp/completion.subp_parameters/src/bar.ads
- testsuite/ada_lsp/completion.subp_parameters/src/main.adb
- testsuite/ada_lsp/completion.subp_parameters/test.json
- testsuite/ada_lsp/completion.subp_parameters/test.yaml
The ALS now sends snippets for subprogram completion items, listing
all the formal parameters of the given subprogram to help users
assigning a value for each of them.
An automatic test has been added and tester-macros.adb has been adapted
to avoid conflicts between the compeltion snippets format and our macros
format.
> T319-027: Add completion for subprogram parameters

- source/ada/lsp-ada_documents.adb
- testsuite/ada_lsp/get_symbol_hier/test.json
For the following enum type:
type Hello_World is (Hello, World);
Don't return "Hello" and "World" in the Document Symbols request,
we are only interested on the type declaration, I.E. "Hello_World".
> SA21-029: Ignore the Enum type values in Document Symbols

- source/ada/lsp-ada_documents.adb
- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-common.adb
- source/ada/lsp-common.ads
- testsuite/ada_lsp/completion.subp_parameters/test.json
Display the hover text of the completion item's declaration in the
'detail' field of the completion item.
This allows to distinguish more easily overloaded subprograms
for instance. This is also what other Microsoft's language servers
do (e.g: Python).
> T327-013: Display hover text for completion items too

- source/spawn/spawn-processes-monitor__posix.adb
- source/spawn/spawn-processes__glib.adb
- source/spawn/spawn-processes__posix.adb
It requires type use visibility for 'in' and 'not in' operations.
> T406-014 Fix compilation on new GNAT Pro compiler.

- source/ada/lsp-ada_documents.adb
- source/ada/lsp-ada_handlers.adb
- source/client/lsp-raw_clients.adb
- source/protocol/lsp-generic_optional.adb
- source/protocol/lsp-messages.adb
- source/protocol/lsp-types.adb
- source/protocol/lsp-types.ads
- source/server/lsp-servers-decode_notification.adb
- source/server/lsp-servers-decode_request.adb
- source/tester/tester-tests.adb
Addresses a number of compiler errors of the form
(sloc): use clause would make operation legal
(sloc): operator for type "(type)" defined at
in the most recent version of GNAT.
> Adapt to new compiler rules for type visibility

- source/ada/lsp-ada_documents.adb
- testsuite/ada_lsp/SA21-029.documentSymbol.with/foo.adb
- testsuite/ada_lsp/SA21-029.documentSymbol.with/test.json
- testsuite/ada_lsp/SA21-029.documentSymbol.with/test.yaml
- testsuite/ada_lsp/get_symbol_hier/test.json
Add Global variables in DocumentSymbols request.
Defensive code when walking through empty nodes.
Add "with" clauses.
> SA21-029: Enhancements for DocumentSymbols

- testsuite/ada_lsp/completion.complex_renames/default.gpr
- testsuite/ada_lsp/completion.complex_renames/main.adb
- testsuite/ada_lsp/completion.complex_renames/parent-children.ads
- testsuite/ada_lsp/completion.complex_renames/parent.ads
- testsuite/ada_lsp/completion.complex_renames/test.json
- testsuite/ada_lsp/completion.complex_renames/test.yaml
This was not working with the old GNAT Studio completion engine
but now works with the ALS.
> R519-005: Add a completion test for complex renames

- source/ada/lsp-ada_documents.adb
- testsuite/ada_lsp/completion.subp_params_dotted_names/default.gpr
- testsuite/ada_lsp/completion.subp_params_dotted_names/src/bar.ads
- testsuite/ada_lsp/completion.subp_params_dotted_names/src/main.adb
- testsuite/ada_lsp/completion.subp_params_dotted_names/test.json
- testsuite/ada_lsp/completion.subp_params_dotted_names/test.yaml
We now use the new libadalang Is_Dot_Call function on the returned
compeltion items to know if we are dealing with a dotted subporgram call
or not, allowing us to distiguish dotted calls, for which we should omit
the first parameter in the returned completion snippets, from subprogram
calls that are prefixed by a package names (e.g: Ada.Text_IO.Put_Line).
An automatic test has also been added.
> T319-027: Handle package prefixes for subp calls completion

- integration/vscode/ada/syntaxes/ada.tmLanguage.json
This PR is intended to add the support for `subtype` in the syntax highlighter of vscode. The syntax is based on the [Ada RM](https://www.adaic.org/resources/add_content/standards/05rm/html/RM-3-2-2.html). All the cases should have been taken into account.
The regex are not always very clean, and I would be happy to discuss to find something better.
> Add support for subtype

- README.md
Hi there,
Neovim v0.5.0 has a built-in LSP client. This client is very barebones (you have to send requests/notification yourself, setup callbacks to react to notifications from the server…). There is a set of default configurations for this client that make using LSP servers with it much smoother.
This set of configuration is available here: https://github.com/neovim/nvim-lsp. I added a configuration file for the ada language server in this PR: https://github.com/neovim/nvim-lsp/pull/171.
The commit I'd like you to merge adds information about using the Ada Language Server with Neovim's set of default configurations. Feel free to edit whatever is unclear/ask for changes :).
> README.md: Add information about Neovim's builtin LSP client

- integration/vscode/ada/syntaxes/ada.tmLanguage.json
I have added a partial support for the syntax highlighting of `aspect_clause`s.
**Limitations**:
- The support is not complete. The `at_clause` construction is not supported by this work (cf. [here](https://www.adaic.org/resources/add_content/standards/05rm/html/RM-13-1.html#I4417)) because I'm not enough familiar with Ada to know how it is used.
- Moreover, in the following construction, I don't know what scope I should give to `attribute_designator` in `for local_name'attribute_designator use expression;`. Then no scope is assigned to it.
> Add aspect_clause support

- integration/vscode/ada/syntaxes/gpr.tmLanguage.json
For my own use I also needed to improve the highlighting support of `.gpr` files.
I added:
- Support for with clause.
- Support for extends keyword in both projects and package.
- Support for package extension.
I also attach an example that should be correctly highlighted for your tests.
```Ada
with "Ada_Drivers_Library/boards/stm32f769_discovery/stm32f769_discovery_sfp.gpr";
project HTTP_Cyclone extends "Ada_Drivers_Library/examples/shared/common/common.gpr" is
for Runtime ("Ada") use STM32F769_Discovery_sfp'Runtime("Ada");
for Target use "arm-eabi";
for Object_Dir use "obj";
for Create_Missing_Dirs use "True";
for Source_Dirs use ("src/**");
package Compiler renames STM32F769_Discovery_SFP.Compiler;
end HTTP_Cyclone;
```
Also, last commit changes `"punctuation.definition.string.ada"` …
> Improve GPR highlighting support

- Makefile
- doc/HACKING.md
- integration/travis/travis.sh
- integration/vscode/ada/.vscode/launch.json
- integration/vscode/ada/package.json
- integration/vscode/ada/run_grammar_tests.sh
- integration/vscode/ada/testsuite/index.ts
- integration/vscode/ada/testsuite/runTests.ts
- integration/vscode/ada/testsuite/tests/simple/simple.test.ts
- integration/vscode/ada/testsuite_grammar/gpr_base/http_cyclone.gpr
- integration/vscode/ada/testsuite_grammar/gpr_base/http_cyclone.gpr.snap
- integration/vscode/ada/testsuite_grammar/hello/hello.adb
- integration/vscode/ada/testsuite_grammar/hello/hello.adb.snap
- integration/vscode/ada/testsuite_grammar/invalid_ada/hello.adb
- integration/vscode/ada/testsuite_grammar/invalid_ada/hello.adb.snap
- integration/vscode/ada/tsconfig.json
Add
*  a VS Code integration test framework based on
https://code.visualstudio.com/api/working-with-extensions/testing-extension
* a VS Code grammar test framework based on the (very nice)
https://github.com/PanAeon/vscode-tmgrammar-test
Add a Makefile target to drive this. Add a note in the documentation.
Schedule this as part of the travis builder on Linux.
Fixes #386
> Initial revision of a testsuite for the VS Code grammars

- source/ada/lsp-ada_handlers.adb
- testsuite/ada_lsp/implementation.aggregates/test.json
Since displaying the base name of the entity's declaration file might
not be sufficient in case of aggregate projects.
> T423-090: Display project name for aggregate project tooltips

- source/ada/lsp-ada_documents.adb
- testsuite/ada_lsp/completion.aggregates.derived_private/default.gpr
- testsuite/ada_lsp/completion.aggregates.derived_private/main.adb
- testsuite/ada_lsp/completion.aggregates.derived_private/test.json
- testsuite/ada_lsp/completion.aggregates.derived_private/test.yaml
When initializing a record that derives from a parent type, the visible
components/discriminants should be specified too.
Also, when the parent is private, aggregate extensions should be used in
the proposed snippets.
> SA14-008: handle aggregate completion of derived types.

- scripts/predefined_completion.py
- source/ada/generated/lsp-predefined_completion-ada2012.ads
- source/ada/lsp-ada_documents.adb
- source/ada/lsp-ada_driver.adb
- source/ada/lsp-common.adb
- source/ada/lsp-common.ads
- source/ada/lsp-predefined_completion.adb
- source/ada/lsp-predefined_completion.ads
- source/protocol/lsp-types.adb
- source/protocol/lsp-types.ads
- testsuite/ada_lsp/completion.subp_parameters/test.json
We now provide basic completion for keywords, aspects, pragmas and
attributes.
While keyword completion is provided directly by LAL, completion items
for pragmas, aspects and attributes are read through a JSON database.
Currently we only have a database for Ada 2012 aspects, pragmas and
keywords: the plan is to have one database per Ada version, and
determine which database should be used depending on the GNAT install
found in the PATH.
Thus, this is work in progress: we need to add a database per version
and we need to refine the behavior for keyword and attributes'
completion (some LAL bits are missing).
> T318-064: Provide completion for predefined item

- source/ada/lsp-ada_documents.adb
Since we only want to display declarations in the Outline and expression
nodes can't contain declarations.
> T702-027: Avoid recursion on documentSymbol request for expressions

- Makefile
- testsuite/drivers/__init__.py
- testsuite/drivers/basic.py
- testsuite/drivers/codecs.py
- testsuite/run-tests
- testsuite/testsuite.py
... without gnatpython.
Make the necessary changes to function profiles and names, and
adjustments to use Python 3.
Remove our implementation of get_test_list, which doesn't return
a ParsedTest: instead, use the documented API to select test
drivers.
> T707-058 Allow the driver to be run from e3

- source/ada/lsp-ada_documents.adb
- source/ada/lsp-ada_documents.ads
- testsuite/ada_lsp/completion.keywords/main.adb
- testsuite/ada_lsp/completion.keywords/test.json
- testsuite/ada_lsp/completion.keywords/test.yaml
In order to avoid proposing keywords right after a '(' for instance.
Aborts basic test for keyword completion has also been added.
> T318-064: Avoid keyword completion after non-whitespace characters

- testsuite/run-tests
This doesn't work under Windows.
> Revert "T717-032 Make run-tests python3 only"

- integration/vscode/ada/advanced/ada.tmLanguage.json
- integration/vscode/ada/testsuite_grammar/nesting/main.adb.snap.advanced
- integration/vscode/ada/testsuite_grammar/types/types.ads.snap.advanced
Hello,
As mentioned in some issues (#495, #496 & #497), the highlighting can look a bit strange sometimes, and some words are highlighted in a strange way with some themes. Look at the screenshot bellow for a such example.
This PR tries to improve this. I don't pretend that everything is working fine, but it improves the highlighting to something better. I already know limitation and cases where it doesn't work. I can work on it with the limited time that I have to make it event much better. But first I would like to have a feedback on this work. I also put another screenshot bellow to see the difference, but I strongly encourage you to test it by yourself.
The screenshots are made with the theme Community Material Theme Ocean.
> Rework highlighting

- source/tester/tester-tests.adb
- testsuite/ada_lsp/README.md
- testsuite/ada_lsp/completion.subp_parameters/test.json
Now the `sortReply` property can contain a composite sorting keys.
It also can point a array nested in an object, like
sortReply: {result: {items: ["label", "detail"]}}
to sort completions in a form of
result: {items: [{title: x, detail: y}, {...}]}
> T618-028 Improve the test driver

- integration/vscode/ada/package.json
It seems #507 fixed most of the issues and now it looks much
better then before.
> Restore advanced syntax highlighter.

- source/ada/lsp-ada_documents.adb
- testsuite/ada_lsp/completion.invisible/aaa.ads
- testsuite/ada_lsp/completion.invisible/test.json
- testsuite/ada_lsp/completion.subp_parameters/test.json
with '(invisible)' text. Also don't provide snippets for
invisible symbols in completions, because we don't know
if this is a "dot call" or normal one.
> T618-028 Mark invisible symbol completion labels

- source/ada/lsp-ada_completion_sets.adb
- source/ada/lsp-ada_completion_sets.ads
- source/ada/lsp-ada_documents.adb
- source/ada/lsp-ada_documents.ads
- source/ada/lsp-ada_handlers.adb
- testsuite/ada_lsp/completion.no_snippet_for_params/main.adb
- testsuite/ada_lsp/completion.no_snippet_for_params/test.json
- testsuite/ada_lsp/completion.no_snippet_for_params/test.yaml
In particular, we don't want to propose subprogram snippets when
giving a completing a subprogram name for an access-to-subprogram
parameter.
> T728-028: Don't propose snippets when providing parameters

- source/protocol/lsp-types.adb
clangd 12.0 sends a simpel string for the allCommitCharacters completion
option, so, instead of crashing, let's accept it.
> T828-037: Allow simple strings for Optional_LSP_String_Vectors

- integration/vscode/ada/advanced/ada.tmLanguage.json
Hello,
This is not a very important change. It just add an highlighting support for preprocessor directives.
Since gnatprep is almost never used, this change is not a big deal, but can be still useful.
> Highlighting: Add support for gnatprep preprocessor directives

- source/ada/lsp-ada_handlers.adb
- testsuite/ada_lsp/definition_parents/test.json
List the overriding subprograms only if we are clicking on a 'usage'
name (e.g: subprogram call) or on abstract subprogram declarations.
> T122-009: Change textDocument/definition behavior

- source/ada/lsp-lal_utils.ads
- testsuite/ada_lsp/T709-018.is_called_by.name_collision/test.json
Map keys are now sorted by text, then by filename, then by sloc
(first by line and then by column).
Test T709-018.is_called_by.name_collision updated since pack1.ads
results now come first than pack2.ads results.
> T908-028 Correct "<" of References_By_Subprogram

- scripts/generate.py
* scripts/generate.py: All files that are to be opened for write and
are to contain text must be opened "w", not "wb".
> Ensure scripts are compatible with both Python 2 and 3

- Makefile
* Makefile (DESTDIR): Defaulted to $prefix, which is defaulted to
/usr/local.
(LIBRARY_FLAGS): Merge the two versions.
(all): Additionally build lsp_client.gpr and lsp_client_glib.gpr.
(install): Don't install tester.gpr or codec_test.gpr. Instead,
install lsp_client.gpr and lsp_client_glib.gpr.
> Generate client libraries

- Makefile
Temporarily: this is needed for the testing infrastructure
internal to AdaCore.
> T916-036 Re-install the tester scripts as part of install

- source/ada/lsp-ada_handlers.adb
Read the value of Find_All_Imprecise in the branch where it is
set.
> Fix an issue with potential read of an uninitialized variable

- testsuite/ada_lsp/T923-019.project_reload.gnatpp/a.adb
- testsuite/ada_lsp/T923-019.project_reload.gnatpp/p.gpr
- testsuite/ada_lsp/T923-019.project_reload.gnatpp/test.json
- testsuite/ada_lsp/T923-019.project_reload.gnatpp/test.yaml
This tests for memory corruption when loading several times
a project that defines gnatpp switches. The corresponding fix
is in libadalang-tools.
> T923-019 add a test

- doc/settings.md
- source/ada/lsp-ada_handlers.adb
"relocateBuildTree" and "rootDir" configuration options have
been added to take in account corresponding GNAT Studio switches
> T306-003 GNAT Studio's relocate-build-tree switch

- README.md
- doc/HACKING.md
- gnat/lsp_server.gpr
- integration/appveyor/appveyor.sh
- integration/travis/travis.sh
- scripts/generate.py
- source/ada/lsp-ada_context_sets.adb
- source/ada/lsp-ada_context_sets.ads
- source/ada/lsp-ada_contexts.adb
- source/ada/lsp-ada_contexts.ads
- source/ada/lsp-ada_file_sets.ads
- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-ada_handlers.ads
- source/ada/lsp-fuzz_decorators.adb
- source/ada/lsp-fuzz_decorators.ads
- source/client/lsp-clients.adb
- source/client/lsp-clients.ads
- source/protocol/generated/lsp-messages-server_notifications.adb
- source/protocol/generated/lsp-messages-server_notifications.ads
- source/protocol/generated/lsp-server_notification_receivers.ads
- source/server/lsp-message_loggers.adb
- source/server/lsp-message_loggers.ads
- source/server/lsp-servers.adb
- source/server/lsp-servers.ads
- subprojects/stubs/ada_libfswatch.gpr
- subprojects/stubs/libfswatch.ads
This adds support for monitoring the filesystem for changes
that might occur in project directories, outside of the IDE.
Add support for `workspace/didChangeWatchedFiles`.
Add an optional dependency on ada_libfswatch.gpr, and document
it. Add support in the travis CI builder to generate it on Linux.
Add a stub project to make the ALS useable without this dependency.
Rework the way files are indexed, to allow reindexing for any
file that might change on disk. In particular, no longer store
in LSP.Ada_Contexts a reference to the "Last_Indexed" file, which
prevented indexing of new files altogether.
> TA09-019 Add support for filesystem monitoring

- source/server/lsp-servers.adb
... an oversight from the previous PR, found through manual
testing.
> TA09-019 fs monitoring: support deleted files, or empty/invalid directories

- source/ada/lsp-ada_contexts.adb
- source/server/lsp-servers.adb
Prevent potential call to Stop_Monitor in case the monitor
was never started.
> TA09-019 filesystem monitoring: better handle exiting

- source/ada/lsp-ada_contexts.adb
- source/ada/lsp-ada_contexts.ads
- source/ada/lsp-ada_handlers.adb
This can cause somes issues with the LAL envs when indexing
a file that already has an analysis unit (e.g: a file opened
at startup).
> T226-048: Avoid reparsing when indexing the project

- gnat/lsp_server.gpr
Needed to be able to relocate the Ada_Language_Server to machines
which don't have the libstdc++ included.
> In static mode, do not link with gcc_eh or libstdc++

- gnat/lsp_server.gpr
Refinement on the previous change: it is bad practice to link
with libc statically under Unix/Linux.
> TC04-011 Do not link libc statically on Linux

- source/spawn/spawn-internal__glib.ads
- source/spawn/spawn-internal__glib_windows.ads
- source/spawn/spawn-internal__windows.ads
to avoid warnings in newer compiler.
> Mark incomplete type declaration as target

- gnat/spawn_glib.gpr
> TB23-030 Fix building libspawn.dll on Windows

- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-lal_utils.adb
- source/ada/lsp-lal_utils.ads
- testsuite/ada_lsp/P107-003.refactoring.underscores/test.json
- testsuite/ada_lsp/SA11-038_Name_Collision/default.gpr
- testsuite/ada_lsp/SA11-038_Name_Collision/main.adb
- testsuite/ada_lsp/SA11-038_Name_Collision/test.json
- testsuite/ada_lsp/SA11-038_Name_Collision/test.yaml
- testsuite/ada_lsp/rename.not_up_to_date/test.json
- testsuite/ada_lsp/rename/rename.json
The existing rename funcitonality was replaced by Laltools' one.
An error message is return if it is detected that the rename operation will
cause problems.
Added one test for a name collision problem.
Output of rename tests with the changes required were sorted by line number.
> SA11-038 Improve Refactoring Rename

- source/protocol/lsp-messages.adb
The ALS uses a system based on the Ada Tags for encoding/
decoding commands associated to a code action. This requires
types with specific tags to be declared: this is the case
for the ALS server but should not be required for LSP clients.
Add defensive programming to allow this.
> T127-013 Fix support for encoding Code Action commands

- source/client/lsp-clients.adb
- source/client/lsp-clients.ads
from client to the server. It's used in the
`window/workDoneProgress/create` server->client request
for example.
> T826-024 Add an aux procedure to return void response

- gnat/lsp_server.gpr
to avoid name clash with gprinstall generated code.
> Replace Build_Kind with Library_Kind

- source/server/lsp-servers.adb
- testsuite/ada_lsp/S510-020.exceptions_reporting/test.json
The stable version of libadalang_tools uses this for invalid
code.
Adjust a test driver to catch another exception.
> U308-004 catch "assertion_failure" an an expected exception

- .vscode/settings.json
- .vscode/tasks.json
- integration/vscode/ada/package.json
- integration/vscode/gnatprove/.vscode/tasks.json
and fix examples by adding `-gnatef` to `tasks.json`
Refs #541
> Let Ada problemMatcher work with absolute path

- source/ada/lsp-ada_contexts.adb
- source/ada/lsp-preprocessor.adb
- source/ada/lsp-unit_providers.adb
- source/ada/lsp-unit_providers.ads
The previous work on preprocessing omitted to use
the default charset from the context when reading
files from disk.
> U304-005 add support for non-latin1 files

- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-lal_utils.adb
- source/ada/lsp-lal_utils.ads
Instead of returning the subprogram spec decl. This is needed
since VS Code has a different way of showing calls than GS: it
highlights all the calls in the editor isteld instead of showing
them in the tree.
> T903-007: Return enclosing subp body decl for incomingCalls

- .github/workflows/build-binaries.sh
- .github/workflows/build-binaries.yml
- Makefile
- source/tester/tester-macros.adb
- source/tester/tester-macros.ads
- source/tester/tester-tests.adb
- testsuite/ada_lsp/README.md
- testsuite/ada_lsp/project_symlinks/makelink.py
- testsuite/ada_lsp/project_symlinks/test.json
- testsuite/ada_lsp/project_symlinks/test.yaml
Use this comman to create symbolic link during test run.
Fix regexp for `${NAME}` macro in tests. Add `DIR`
into environment variables.
> U315-010 Add `shell` command to ALS tester driver

- source/ada/lsp-ada_handlers-refactor_change_parameter_mode.adb
- source/ada/lsp-ada_handlers-refactor_remove_parameter.adb
- testsuite/ada_lsp/U416-030.refactor_change_parameter_mode_0/default.gpr
- testsuite/ada_lsp/U416-030.refactor_change_parameter_mode_0/main.adb
- testsuite/ada_lsp/U416-030.refactor_change_parameter_mode_0/test.json
- testsuite/ada_lsp/U416-030.refactor_change_parameter_mode_0/test.yaml
- testsuite/ada_lsp/U416-030.refactor_remove_parameter_0/default.gpr
- testsuite/ada_lsp/U416-030.refactor_remove_parameter_0/main.adb
- testsuite/ada_lsp/U416-030.refactor_remove_parameter_0/test.json
- testsuite/ada_lsp/U416-030.refactor_remove_parameter_0/test.yaml
Fix the Change Parameter Mode and Remove Parameter refactoring tools when these are applied to a range of parameters instead of an unique parameter.
Without this fix, the refactoring tools are only applied to the first parameter in the range.
Add a test case for each refactoring.
> U416-030 Fix Change Subp Signatures refactorings

- scripts/generate.py
- source/ada/lsp-ada_contexts.adb
- source/ada/lsp-ada_contexts.ads
- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-lal_utils.adb
- source/ada/lsp-lal_utils.ads
- source/client/lsp-clients.adb
- source/client/lsp-clients.ads
- source/protocol/generated/lsp-messages-server_requests.ads
- testsuite/ada_lsp/T723-027.signatureHelp.nested/default.gpr
- testsuite/ada_lsp/T723-027.signatureHelp.nested/foo.adb
- testsuite/ada_lsp/T723-027.signatureHelp.nested/test.json
- testsuite/ada_lsp/T723-027.signatureHelp.nested/test.yaml
- testsuite/ada_lsp/T723-027.signatureHelp.overloaded/default.gpr
- testsuite/ada_lsp/T723-027.signatureHelp.overloaded/foo.adb
- testsuite/ada_lsp/T723-027.signatureHelp.overloaded/test.json
- testsuite/ada_lsp/T723-027.signatureHelp.overloaded/test.yaml
- testsuite/ada_lsp/T723-027.signatureHelp.simple/default.gpr
- testsuite/ada_lsp/T723-027.signatureHelp.simple/foo.adb
- testsuite/ada_lsp/T723-027.signatureHelp.simple/test.json
- testsuite/ada_lsp/T723-027.signatureHelp.simple/test.yaml
Use P_All_Env_Elements and filter the returned node
to find all the function declaration with the same name.
Fix param type in the generated spec.
Add tests.
> T723-027: Implement SignatureHelp

- source/ada/lsp-ada_contexts.adb
- source/ada/lsp-ada_file_sets.adb
- source/ada/lsp-ada_file_sets.ads
to prevent STALE_REFERENCE_ERROR. Replace Ada_Node with node's
Source_Location and find corresponding node at the query time
(it could be costly however).
Close #633
> U126-028 Don't keep Ada_Node in the global name index

- gnat/lsp_server.gpr
Do this in all cases, rather than letting gprbuild detect it.
Tentative workaround for an issue with gpr2.
> U429-018 Pass "g++" as the Linker

- testsuite/drivers/basic.py
- testsuite/drivers/codecs.py
e3-testsuite-driver relies on rlimit to implement timeouts,
and this does not seem to work on GitHub Action machines.
Deactivate this timeout, and rely instead on the fine-grained
timeout mechanism implemented by the test runner.
> T608-018 Deactivate timeout in the driver

- .github/workflows/build-binaries.yml
To generate CHANGELOG.md we need all tag commits in the
checkouted repositiory, so we should disable --depth=1 on
repository checkout.
> Fix CHANGELOG.md generation on tag/release

- source/ada/lsp-ada_handlers.adb
- testsuite/.als/traces.cfg
These messages are noisy and most often uninteresting.
Add a trace to allow printing them, and checking for them
in tests.
Closes #691
> U526-026 Silence notification for imprecise navigation

- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-ada_handlers.ads
map instead of Document_URI type. This way we fix
errors on case-insensitive file systems, where the
same file can be pointed by distinct URIs, like
`file:///z:/a.adb` and `file:///Z:/a.adb`.
> U301-023 Use Virtual_File as a key in Open_Documnets

- source/ada/lsp-ada_contexts.adb
- source/ada/lsp-ada_contexts.ads
- source/ada/lsp-ada_file_sets.adb
- source/ada/lsp-ada_file_sets.ads
- source/ada/lsp-ada_handlers.adb
So we can look for a symbol with a distinct URI
(like `file:///z:/a.adb` instead of `file:///Z:/a.adb`).
> U301-023 Use Virtual_File as a key in symbol index

- source/ada/lsp-ada_contexts.adb
- source/ada/lsp-ada_contexts.ads
- source/ada/lsp-ada_handlers.adb
- testsuite/ada_lsp/U614-038.edits.no_project/otherdir/a.ads
- testsuite/ada_lsp/U614-038.edits.no_project/test.json
- testsuite/ada_lsp/U614-038.edits.no_project/test.yaml
The modification for files are applied only in the contexts
where the files belong. When there is no project loaded and
the file is in a separate directory, no context accepts this
file, and the modifications are not taken into account.
Fix this by making the "fallback" context accept all
files.
> U614-038 Improve support for files detached from context

- source/ada/lsp-ada_contexts.adb
- source/ada/lsp-ada_contexts.ads
- source/ada/lsp-ada_documents.adb
- source/ada/lsp-ada_documents.ads
- source/ada/lsp-ada_file_sets.adb
- source/ada/lsp-ada_file_sets.ads
- source/ada/lsp-ada_handlers-invisibles.adb
- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-lal_utils.adb
- source/ada/lsp-lal_utils.ads
- testsuite/ada_lsp/completion.subp_parameters/test.json
Make completion return the same symbols as for non-open
files. To do this move Ada_Node predicates (filters) to
LSP.LAL_Utils and reuse them in lsp-ada_handlers-invisibles.adb
and in lsp-ada_file_sets.adb.
Return more symbols in "workspace symbols" request:
return symbols from package body and package private part
also. It could help navigation in some situations.
Fix the testcase.
> U622-019 Fix invisible symbol completion in open files

- source/ada/lsp-ada_handlers.adb
In some situation a new request comes after the last file is indexed.
Leaving progress report loop in this situation prevents from sending
end progress message, because we never come to the loop again.
> Fix report progress code

- testsuite/run-tests
e3-testsuite does not support direct access to YAML files: use the
ReportIndex API to access test results data instead, which works with
newer versions of e3-testsuite.
> run-tests: switch to the report index API

- source/ada/lsp-ada_documents.adb
To avoid the ' (invisible)' suffix in the completion items' labels
being matched when filtering completion.
> U729-019: set filterText for invisible symbols completion

- integration/vscode/ada/ada-snippets.json
- integration/vscode/ada/gpr-snippets.json
fixes #694
Replaces the hard coded triple-spaces in snippets with `\t`, which VS Code replaces with the configured indentation when the snippet is expanded.
Examples with `package` snippet (may need to copy somewhere that shows invisibles)
```
-- 3 spaces
package Name is
pragma Preelaborate;
private
end Name;
-- 8 spaces
package Name is
pragma Preelaborate;
private
end Name;
-- tabs
package Name is
pragma Preelaborate;
private
end Name;
```
> [VS Code] Fix snippet indentation

- integration/vscode/ada/advanced/ada.tmLanguage.json
Syntax highlighting currently fails on the following program due to the task body being inside of the `declare` section
```
with Ada.Text_IO;
procedure Example is
begin
declare
task My_Task;
task body My_Task is
begin
for i in 1 .. 5 loop
Ada.Text_IO.Put_Line(i'Image);
end loop;
end My_Task;
begin
null;
end;
end Example;
```
Fortunately, the TextMate grammar follows the [Ada grammar](https://www.adaic.org/resources/add_content/standards/05rm/html/RM-P.html) closely, so a fix is straightforward: insert the [`#body`](https://github.com/AdaCore/ada_language_server/blob/cab0a492ce38a907847f559cda1b43435d7e4187/integration/vscode/ada/advanced/ada.tmLanguage.json#L410) rule inside of the declare section of the [`#block_statement`](https://github.com/AdaCore/ada_language_server/blob/cab0a492ce38a …
> [VS Code] Grammar: add `body` patterns to declare section

- doc/README.md
Calls and Called_By are now implemented using the incomingCalls
and outgoingCalls request, the related documentation was removed
but not these links
> T903-007: Remove dead link

- source/ada/lsp-ada_completions-names.adb
- source/ada/lsp-ada_completions.adb
- source/ada/lsp-ada_completions.ads
- source/ada/lsp-ada_documents.adb
- source/ada/lsp-ada_documents.ads
- source/ada/lsp-ada_handlers-invisibles.adb
- source/ada/lsp-ada_handlers.adb
... by keeping track of the order returned by LAL itself, and using
it to set the sortText accordingly.
This allows the client to sort results in a better way, in line with
LAL results.
> U720-009: improve sorting for completionItems

- Makefile
to keep `.exe` extension on Windows. Closes #767
> Rewrite a rule for copying server executable

- Makefile
to be compatible with our cygwin environment.
> Drop `-v` option from `cp` command

- source/ada/lsp-lal_utils.adb
- testsuite/ada_lsp/T723-027.signatureHelp.nested/test.json
- testsuite/ada_lsp/T723-027.signatureHelp.overloaded/test.json
- testsuite/ada_lsp/T723-027.signatureHelp.simple/test.json
- testsuite/ada_lsp/U429-030.signatureHelp.dot_call/test.json
LAL error recovery create a similar tree for "Foo (1|" and "Foo (1,|"
thus we must add token analysis to detect a ",".
Adapts the tests.
> U804-021: Handle "," in signatureHelp

- source/ada/lsp-ada_completions.adb
- source/ada/lsp-ada_documents.adb
- source/ada/lsp-ada_documents.ads
- testsuite/ada_lsp/completion.invisible5/default.gpr
- testsuite/ada_lsp/completion.invisible5/main.adb
- testsuite/ada_lsp/completion.invisible5/pkg-ada.ads
- testsuite/ada_lsp/completion.invisible5/pkg.ads
- testsuite/ada_lsp/completion.invisible5/test.json
- testsuite/ada_lsp/completion.invisible5/test.yaml
there is some visible name with the same label in result.
For instance, if we have `Pkg.Ada` in the project and
`with Ada;` in unit clauses, we shouldn't propose `Pkg.Ada`
as invisible completion for `Ada` identifier, because it
won't work any way. `Ada` is already visible and the
second package can't become visible even if we append
`with Pkg.Ada; use Pkg;` clauses.
> U729-020 Don't send invisible name in completion if

- source/ada/lsp-ada_documents.adb
- source/ada/lsp-ada_handlers-invisibles.adb
- source/ada/lsp-lal_utils.adb
- testsuite/ada_lsp/completion.invisible3/test.json
- testsuite/ada_lsp/completion.subp_params_dotted_names/test.json
When parsing a generic package declaration LAL will return
GenericPackageDecl(GenericPackageInternal(...)) at this point
To prevent duplicate we must ignore either the GenericPackageDecl
or the GenericPackageInternal => the completion returns the second.
(Also Ada_Base_Package_Decl contains GenericPackageInternal and not
GenericPackageDecl)
Also fix a missing conversion between SymbolKind and CompletionKind
Adapts tests.
> U831-003: Handle generic package in Get_Decl_Kind

- source/server/lsp-servers.ads
... to prevent craches on deep nesting calls in LAL.
> U827-008 Increase size of stack for request processing task

- source/ada/lsp-ada_handlers.adb
- testsuite/ada_lsp/completion.lazy_computation/default.gpr
- testsuite/ada_lsp/completion.lazy_computation/main.adb
- testsuite/ada_lsp/completion.lazy_computation/test.ads
- testsuite/ada_lsp/completion.lazy_computation/test.json
- testsuite/ada_lsp/completion.lazy_computation/test.yaml
. Some completion items (predefined keywords, attributes...) already
have their doc pre-computed, so don't try to resolve it lazily.
. Add an automatic test.
> U622-021: Fix bug in lazy completion and add a test

- Makefile
This allows to build the vscode extension in the environment
development that has the gtk3 closure, avoiding an issue with
zlib versions mismatch.
> Empty LD_LIBRARY_PATH seen by npm

- source/ada/lsp-ada_handlers.adb
- source/protocol/lsp-messages.ads
- testsuite/ada_lsp/U910-043.client_capabilities.optional/test.json
- testsuite/ada_lsp/U910-043.client_capabilities.optional/test.yaml
Some client capabilities like "moniker" were not defined as
optional => The server was crashing if their value was "null".
> U910-043: Fix parsing error for optional client capabilities

- source/ada/lsp-ada_handlers.adb
- source/server/lsp-generic_cancel_check.ads
- testsuite/ada_lsp/workspace_symbol/test.json
Do not process too small pattern because this produces a huge
response that is useless and costs a while.
> T826-026 Workspace_Symbols Request

- integration/vscode/ada/package.json
Needed on our production Windows machines.
> Invoke npm commands with "node" rather than the shebang

- source/ada/lsp-ada_completions-aggregates.adb
- source/ada/lsp-ada_completions-aggregates.ads
- source/ada/lsp-ada_completions-aspects.adb
- source/ada/lsp-ada_completions-aspects.ads
- source/ada/lsp-ada_completions-keywords.adb
- source/ada/lsp-ada_completions-keywords.ads
- source/ada/lsp-ada_completions-names.adb
- source/ada/lsp-ada_completions-names.ads
- source/ada/lsp-ada_completions-parameters.adb
- source/ada/lsp-ada_completions-parameters.ads
- source/ada/lsp-ada_completions-pragmas.adb
- source/ada/lsp-ada_completions-pragmas.ads
- source/ada/lsp-ada_completions.ads
- source/ada/lsp-ada_documents.adb
- source/ada/lsp-ada_documents.ads
- source/ada/lsp-ada_handlers-invisibles.adb
- source/ada/lsp-ada_handlers-invisibles.ads
- source/ada/lsp-ada_handlers.adb
- testsuite/ada_lsp/U913-028.completion.params/test.json
- testsuite/ada_lsp/U915-024.completion.invisible_snippets/test.json
- testsuite/ada_lsp/completion.invisible.runtime/test.json
- testsuite/ada_lsp/completion.invisible/test.json
- testsuite/ada_lsp/completion.invisible3/test.json
- testsuite/ada_lsp/completion.invisible4/test.json
- testsuite/ada_lsp/completion.lazy_computation/test.json
- Add documentation for "Params of X" item (use lazy computation
if possible)
- Keep the results grouped by family
- Fix the kind of param item
- Fix sortText for invisible symbols
Adapt tests
> U929-049: Completion param provider enhancement

- README.md
Contrary to cocvim, this plugin does not require node.js.
> Add integration with vim-lsp

- .github/workflows/build-binaries.yml
The `gnat` directory doesn't cause an error in alire any more.
Also drop python removal from GNAT prefix, because we don't
use GNAT CE any more
> U922-009 Drop GitHub CI workarounds

- source/ada/lsp-ada_handlers.adb
This is noise most of the time, as gprbuild now creates
the missing directories by default.
> UB10-025 Do not raise errors for missing object dirs

- integration/vscode/ada/src/alsClientFeatures.ts
- integration/vscode/ada/src/extension.ts
- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-ada_handlers.ads
- source/protocol/generated/lsp-message_io.adb
- source/protocol/lsp-messages.ads
- source/protocol/lsp-types.ads
- source/tester/tester-tests.adb
- testsuite/ada_lsp/README.md
- testsuite/ada_lsp/refactoring_add_parameter/S314-015/test.yaml
- testsuite/ada_lsp/refactoring_add_parameter/UA25-015/default.gpr
- testsuite/ada_lsp/refactoring_add_parameter/UA25-015/main.adb
- testsuite/ada_lsp/refactoring_add_parameter/UA25-015/test.json
- testsuite/ada_lsp/refactoring_add_parameter/UA25-015/test.yaml
Added check to confirm that client supports advanced refactorings before sending advanced refactoring code actions.
Added test case and adjusted existing ones by adding a <DOES_NOT_HAVE> pattern. This pattern is used to confirm that the server does not send advanced refactoring code actions to clients that don't support it.
> UA25-015 Added Experimental Client Capabilities and <DOES_NOT_HAVE> pattern

- source/ada/lsp-ada_completions-names.adb
- source/tester/tester-tests.adb
results, because it's an internal LAL package.
Also add a fix for `tester-run --debug` command.
> UB30-020 Hide `no_root_types_` name from completion

- .github/workflows/pack-binaries.sh
by forcing it with `--unsafe-perm` option.
> Fix `npm install -g vsce`

- source/ada/lsp-ada_handlers.adb
An error will happen if the request is handled after the document
has been closed.
> UC06-052: Add defensive code in Hightlight request

- gnat/lsp.gpr
At the moment we can't transition to using [] for array aggregates,
since we support older compilers: silence the warning about these
in development mode.
> Deactivate warnings on () for array aggregates

- integration/vscode/ada/src/extension.ts
The predefined tasks for gprbuild should be recomputed when the scenario
variables change, to provide the right command line when building.
> UC01-021: recompute predefined tasks when scenario vars change

- source/ada/lsp-ada_handlers.adb
- source/protocol/generated/lsp-message_io.adb
- source/protocol/lsp-messages.ads
This can be used by GS to know which is the log file of the
current ALS session. Needed to include the correct log file in
bug report archives.
> UB29-023: Provide log file name in programInfo

- source/ada/lsp-ada_handlers.adb
- testsuite/ada_lsp/T318-086.suppress.separates.0/test.json
- testsuite/ada_lsp/refactoring_add_parameter/S314-015/test.json
- testsuite/ada_lsp/refactoring_add_parameter/UA25-015/test.json
Because we use the project's source directories to compute the FileFilters
of these capabilities (i.e: the files that should be monitored for file
operations' notifications).
> U415-027: project should be loaded before FileOperations capabilities

- source/ada/lsp-ada_handlers.adb
Author: Eric Botcazou <ebotcazou@adacore.com>
The usage of the "=" operator with an overloaded left operand with String
and Unbounded_String interpretations and a String right operand is illegal
because it is ambiguous.  This will be diagnosed by an enhanced compiler:
lsp-ada_handlers.adb:5589:65:
error: ambiguous expression (cannot resolve "=")
lsp-ada_handlers.adb:5589:65:
error: possible interpretation at a-strunb.ads:248
lsp-ada_handlers.adb:5589:65:
error: possible interpretation in package Standard
TN: V112-041
> Fix ambiguity for "=" operator involving String and Unbounded_String

- .github/workflows/build-binaries.sh
- integration/vscode/ada/package.json
And interrupt the build if any is found.
> UB11-011 Call "npm audit" to check for vulnerabilities

- source/ada/lsp-ada_contexts.adb
- source/ada/lsp-ada_contexts.ads
- source/ada/lsp-ada_documents.adb
- source/ada/lsp-ada_documents.ads
- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-lal_utils.adb
- testsuite/ada_lsp/U909-007.signatureHelp.closing_par/default.gpr
- testsuite/ada_lsp/U909-007.signatureHelp.closing_par/foo.adb
- testsuite/ada_lsp/U909-007.signatureHelp.closing_par/test.json
- testsuite/ada_lsp/U909-007.signatureHelp.closing_par/test.yaml
- testsuite/ada_lsp/U909-007.signatureHelp.type_cast/default.gpr
- testsuite/ada_lsp/U909-007.signatureHelp.type_cast/foo.adb
- testsuite/ada_lsp/U909-007.signatureHelp.type_cast/test.json
- testsuite/ada_lsp/U909-007.signatureHelp.type_cast/test.yaml
- Better detection of "," => the previous solution was not working
when having a closing parenthese
- Don't close the previous signatureHelp when writing a type cast
- Better handling of ErrorStmt => lal.lookup will not find the
proper node if we are at its sloc_end which is often the case
for the cursor position while typing: use the position before
the cursor: try at the Location before the cursor and after it.
- Better handling of closing parenthesis for nested calls
Add and adapt tests.
> U909-007: signatureHelp improvements

- source/ada/lsp-ada_completions-attributes.adb
- testsuite/ada_lsp/V216-030.completion.attribute_in_decl/default.gpr
- testsuite/ada_lsp/V216-030.completion.attribute_in_decl/main.adb
- testsuite/ada_lsp/V216-030.completion.attribute_in_decl/test.json
- testsuite/ada_lsp/V216-030.completion.attribute_in_decl/test.yaml
We should not rely on the current node's text to be the completion
prefix when the user just typed "'". Instead, we should set it to
null in order to list all the possible attributes.
Add an automatic test.
> V216-030: Fix attribute completion in declarations

- source/ada/lsp-ada_contexts.adb
Used to investigate memory issues: this trace can log the files being
indexed and the number of diagnostics created by Libadalang.
> V303-003 Add a trace for file indexing

- gnat/lsp_server.gpr
In `lsp.gpr` we have:
``` ada
Common_Ada_Switches := (
--  Generate debug information even in production: this is useful to
--  get meaningful tracebacks.
"-g",
--  Compile with "-gnatX" to support the "[]" syntax for array
--  aggregates: this is the common ground between all compilers
--  commonly used to build the language server.
"-gnatX");
```
Note in specific the comment about `-gnatX`.
We define specific switches for `lsp-ada_driver.adb` in `lsp_server.gpr`.
So I propose adding `-gnatX` to `lsp-ada_driver.adb` too so that we can use the new arrays syntax.
> Support Ada 2022 arrays

- source/ada/lsp-ada_completions-aggregates.adb
- testsuite/ada_lsp/completion.aggregates.derived_types/test.json
- testsuite/ada_lsp/completion.aggregates.simple/test.json
We don't need to put the parameter's name in the snippet's
placeholders when using named notation, since these names
are already visible.
> V223-056: Reduce length of named aggregate snippets

- source/ada/lsp-ada_handlers.adb
- source/protocol/lsp-messages.adb
Fixes the following warning when using GNAT Pro 23.0w (20220411-112)
```
lsp-messages.adb:2878:19: (style) bad casing of "value" declared at lsp-messages.ads:7679                                                                                                                                                                                                                                     
lsp-ada_handlers.adb:790:31: (style) bad casing of "result" declared at lsp-generic_responses.ads:40, instance at lsp-messages-server_responses.ads:306                                                                                                                                                                       
lsp-ada_handlers.adb:807:22: (style) bad casing of "error" declared at …
```
> Fix bad casing warnings

- source/ada/lsp-ada_handlers.adb
The modification of prepareCallHierarchy returning the body
and not the spec had for side effect of using a non-indexed
document resulting in empty result (only the "ads" are indexed)
> V419-041: Incoming Calls for entity outside of the project

- .github/workflows/pack-binaries.sh
Since `23.0.4` CHANGELOG.md isn't generated correctly,
it misses the last tag entry. The investigation shows that
GitHub Action checkout SHA for the tag, but not the tag annotation.
For instance:
```
git rev-parse refs/tags/23.0.5
05ea548d65e6607e4fbb0facb0aee94be1f702ee
git fetch --no-tags origin +de660fc7f50123e22a82b9363e095accd834c6c9:refs/tags/23.0.5
git rev-parse refs/tags/23.0.5
de660fc7f50123e22a82b9363e095accd834c6c9
```
So `de660fc` replaces `05ea548d` in tag `23.0.5`.
We drop the tag and fetch all tags from the origin again.
> Refetch tags from origin to fix CHANGELOG.md generation

- .github/workflows/pack-binaries.sh
- integration/vscode/ada/.vscodeignore
- integration/vscode/ada/package.json
Install esbuild and use it before packaging vscode extension
to reduce number of packaged files, speed extension up.
This fixes warnings on `vsce publish` and `vsce package`.
According to the guide:
https://code.visualstudio.com/api/working-with-extensions/bundling-extension
> Bundle vscode extension on publishing

- source/tester/tester-tests.adb
- testsuite/ada_lsp/README.md
- testsuite/ada_lsp/aggregate.is_called_by/test.json
- testsuite/ada_lsp/show_dependencies.aggregate/test.json
- testsuite/ada_lsp/type_definition.aggregate/test.json
Extend `sortReply` to work with keys nested in objects
inside JSON array. With this sort complex reply JSON to have
more stable tests.
For instance
```json
"sortReply": {"result": {"range": {"start": "line"}}}
```
will sort `result` JSON array using `X.range.start.line` as
a sorting key, where `X` is an array item.
Allow integer JSON values as sorting keys also.
> Allow more complex sorting in LSP tests.

- source/ada/lsp-ada_completions-names.adb
- source/ada/lsp-ada_completions.adb
- source/ada/lsp-ada_completions.ads
- source/ada/lsp-ada_documents.adb
- source/ada/lsp-ada_documents.ads
- source/ada/lsp-ada_handlers-invisibles.adb
- source/ada/lsp-ada_handlers.adb
- testsuite/ada_lsp/U915-024.completion.invisible_snippets/test.json
- testsuite/ada_lsp/U921-010.completion.no_generic_duplicates/test.json
- testsuite/ada_lsp/completion.duplicates/test.json
- testsuite/ada_lsp/completion.invisible.runtime/test.json
- testsuite/ada_lsp/completion.invisible/test.json
- testsuite/ada_lsp/completion.invisible3/test.json
- testsuite/ada_lsp/completion.invisible4/test.json
- testsuite/ada_lsp/completion.invisible5/test.json
- testsuite/ada_lsp/completion.lazy_computation/test.json
In order to place items with an higher weight at the
top of the completion window.
> V614-021: Use completion weight in sortText

- source/ada/lsp-ada_contexts.adb
- source/ada/lsp-ada_contexts.ads
- source/ada/lsp-ada_documents.adb
- source/ada/lsp-ada_documents.ads
- source/ada/lsp-ada_handlers.adb
- testsuite/ada_lsp/T527-019.range_formatting/test.json
When setting the ALS.PARTIAL_GNATPP=yes trace, On_Range_Formatting_Request now uses partial gnatpp to perform a range formatting.
> Add partial gnatpp option to On_Range_Formatting_Request handler

- source/ada/lsp-ada_contexts.adb
- source/ada/lsp-ada_handlers.adb
- testsuite/ada_lsp/V701-011.formatting.options_precedence/default.gpr
- testsuite/ada_lsp/V701-011.formatting.options_precedence/main.adb
- testsuite/ada_lsp/V701-011.formatting.options_precedence/test.json
- testsuite/ada_lsp/V701-011.formatting.options_precedence/test.yaml
Options explicitly set in the project file should have precedence
over LSP options set by the client.
> V701-011: Fix precedence of pretty printer options

- source/ada/lsp-ada_documents.adb
- testsuite/ada_lsp/V705-026.completion.predefined_types/default.gpr
- testsuite/ada_lsp/V705-026.completion.predefined_types/main.adb
- testsuite/ada_lsp/V705-026.completion.predefined_types/test.json
- testsuite/ada_lsp/V705-026.completion.predefined_types/test.yaml
When computing completion items' details, compute the documentation
immediately for predefined types (e.g: Integer) since the standard
package does not correspond to any actual URI.
> V705-026: Compute predefined types' completion doc immediately

- source/ada/lsp-ada_documents.adb
- source/ada/lsp-ada_highlighters.adb
- source/ada/lsp-ada_highlighters.ads
- testsuite/ada_lsp/V628-012.highlighting.defining_names/default.gpr
- testsuite/ada_lsp/V628-012.highlighting.defining_names/foo.adb
- testsuite/ada_lsp/V628-012.highlighting.defining_names/test.json
- testsuite/ada_lsp/V628-012.highlighting.defining_names/test.yaml
Fix "Basic decl having multiple defining names" property errors.
Add generic exception handler and log the error.
Add simple test.
> V628-012: Improve highlighter robustness

- scripts/traces_to_test.py
- source/ada/lsp-ada_documents.adb
- testsuite/ada_lsp/range_formatting/UB30-006_range_format_whole_document/default.gpr
- testsuite/ada_lsp/range_formatting/UB30-006_range_format_whole_document/main.adb
- testsuite/ada_lsp/range_formatting/UB30-006_range_format_whole_document/test.json
- testsuite/ada_lsp/range_formatting/UB30-006_range_format_whole_document/test.yaml
If the user selects from the procedure name `Main` to the procedure end label `Main`, the whole file needs to be formatted. This PR fixes an exception that was being raised when converting from `Source_Location_Range` to `Span`.
```ada
procedure Main is
begin
declare
A : Integer;
begin
null;
end;
end Main;
```
> UB30-006 Fix exception raised when range formatting the whole document

- source/tester/tester-tests.adb
- source/tester/tester-tests.ads
- testsuite/ada_lsp/SC28-001.named.parameters.0/SC28-001.named.parameters.0.json
- testsuite/ada_lsp/completion.aggregates.derived_private/test.json
This prevents test failures like this:
```
task server.input_task_0000000006F6B0B0 terminated by unhandled exception
raised CONSTRAINT_ERROR : LSP.Servers.Request_Maps.Delete: attempt to delete key not in map
[/home/runner/work/ada_language_server/ada_language_server/.obj/server/ada_language_server]
0x14420fd lsp__servers__request_maps__delete at ???
0x145d8c4 lsp__servers__input_task_typeTB at ???
```
> Ensure that a test has unique request ids.

- source/ada/lsp-ada_handlers-refactor_add_parameter.adb
- source/ada/lsp-ada_handlers-refactor_change_parameter_mode.adb
- source/ada/lsp-ada_handlers-refactor_change_parameters_default_value.adb
- source/ada/lsp-ada_handlers-refactor_change_parameters_type.adb
- source/ada/lsp-ada_handlers-refactor_extract_subprogram.adb
- source/ada/lsp-ada_handlers-refactor_imports_commands.adb
- source/ada/lsp-ada_handlers-refactor_introduce_parameter.adb
- source/ada/lsp-ada_handlers-refactor_move_parameter.adb
- source/ada/lsp-ada_handlers-refactor_pull_up_declaration.adb
- source/ada/lsp-ada_handlers-refactor_remove_parameter.adb
- source/ada/lsp-ada_handlers-refactor_suppress_seperate.adb
See this commit in laltools:
https://github.com/AdaCore/libadalang-tools/commit/68ffb694053abefd74d123dee250450d576a6aa7
If any exception is raised by Is_<Refactoring_Tool>_Available, it is now logged and False is returned.
If any exception is raised by <Refactoring_Tool>.Refactor, it is now logged and No_Refactoring_Edits is returned.
To enable the logs, add `LALTOOLS.REFACTOR=yes` to the ALS traces.
This patches:
- refactors the ALS part according to the changes in laltools
- adds an extra exception handler when executing the refactoring code actions
- Improves the failed request message shown to the user
> V801-024 Add exception handlers and logs to the refactoring tools

- integration/vscode/ada/package.json
- integration/vscode/ada/src/extension.ts
- integration/vscode/ada/src/gnatproveTaskProvider.ts
The command is based on the LSP DocumentSymbols request to
retrieve the enclosing subprogram, if any.
> V809-013: Add 'subprogram box' command

- integration/vscode/ada/package.json
Using VS Code Extension Pack mechanism. This allows to package
the extensions mentioned in package.json when creating the .vsix
file.
> U722-033: Package Native Debug extension

- integration/vscode/ada/package.json
By prefixing them by 'Ada: ' (like other extensions do) and
by adding when clauses (i.e: filters) for their associated key
shortcuts and the command palette.
> V809-025: Make our commands Ada-specific

- source/ada/lsp-ada_completions-generic_assoc.adb
We now display the text that will be inserted for each individual
parameter listed when opening a parenthesis.
This is useful to distinguish parameter completion from other
variables that might have the same name.
> V818-002: Add minimal doc for parameter completion

- source/ada/lsp-ada_completions-names.adb
- testsuite/ada_lsp/completion.dotted_call.keyword/bar.ads
- testsuite/ada_lsp/completion.dotted_call.keyword/default.gpr
- testsuite/ada_lsp/completion.dotted_call.keyword/main.adb
- testsuite/ada_lsp/completion.dotted_call.keyword/test.json
- testsuite/ada_lsp/completion.dotted_call.keyword/test.yaml
Add extra error recovery to detect dotted names even when having
Obj.XXX and XXX a keyword (for exemple Obj.Loop or Obj.Do)
Add a test.
> V511-027: Fix snippet for DottedName with Keywords

- source/ada/lsp-ada_completions-generic_assoc.adb
- source/ada/lsp-ada_completions-names.adb
- source/ada/lsp-ada_completions-parameters.ads
- source/ada/lsp-ada_completions.adb
- source/ada/lsp-ada_completions.ads
- source/ada/lsp-ada_contexts.ads
- source/ada/lsp-ada_documents.adb
- source/ada/lsp-ada_documents.ads
- source/ada/lsp-ada_handlers.adb
- testsuite/ada_lsp/U913-028.completion.params/test.json
- testsuite/ada_lsp/completion.snippet.formatting/default.gpr
- testsuite/ada_lsp/completion.snippet.formatting/foo.adb
- testsuite/ada_lsp/completion.snippet.formatting/test.json
- testsuite/ada_lsp/completion.snippet.formatting/test.yaml
- testsuite/ada_lsp/completion.snippet.formatting/traces.cfg
- testsuite/ada_lsp/completion.snippet.formatting2/default.gpr
- testsuite/ada_lsp/completion.snippet.formatting2/foo.adb
- testsuite/ada_lsp/completion.snippet.formatting2/test.json
- testsuite/ada_lsp/completion.snippet.formatting2/test.yaml
- testsuite/ada_lsp/completion.snippet.formatting2/traces.cfg
Encode snippet in pseudo Ada code, run PP and decode it.
When successfull, it will generate a textEdit for the
completionItem.
Enforce PP switches to have the parameter aligned: it can
be disabled via a trace which is used to avoid updating
all the snippet tests.
Add tests with the trace disabled to check the PP behavior
on snippets.
> V511-027: Run PP on completion snippet

- source/ada/lsp-ada_handlers.adb
We can get a null node if the cursor is located on a comment
or an empty line for instance.
In that case, don't try to analyze the node to see which codeActions
should be available.
Add a minimal test.
> V823-006: Add nullity check in Code_Action handler

- source/ada/lsp-ada_contexts.adb
> V624-007: clear gnatpp's template tables

- .github/workflows/build-binaries.sh
- .github/workflows/build-binaries.yml
because they are deprecated. Drop `libgpr2` building, because `libgpr2` is deployed with `libadalang` binaries as a dependency.
> VB28-039 Update Ubuntu and Mac OS X on GitHub CI

- .github/workflows/build-binaries.sh
- .github/workflows/build-binaries.yml
Stop building ALS in `debug` mode. Stop releasing the extension with debug information, because they are not used and confuses VS Code users.
Also fix mounting `/opt` on Windows.
> Drop development builds and releases.

- gnat/lsp_server.gpr
to avoid linking error:
libgmp.a(tdiv_r.o):(.text+0x2ec): more undefined references
to `__stack_chk_fail' follow
> Add `-fstack-protector` switch on Windows
