- source/ada/lsp-ada_contexts.adb
- source/ada/lsp-ada_contexts.ads
- source/ada/lsp-ada_cross_reference_services.adb
- source/ada/lsp-ada_cross_reference_services.ads
- source/ada/lsp-ada_documents.adb
- source/ada/lsp-ada_documents.ads
- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-ada_handlers.ads
Tested on VS Code (Right click on a definition > Find All References) and seems to work just fine :)
> Added find_all_refs feature

- integration/travis/Dockerfile
We drop preinstalled gnatcoll and use one built with libadalang
> Fix Travis CI

- Makefile
- gnat/tester.gpr
- integration/travis/travis.sh
- source/tester/tester-run.adb
- source/tester/tester-tests.adb
- source/tester/tester-tests.ads
- source/tester/tester.ads
- tester.md
- testsuite/ada_lsp/0001-start_stop.json
At first step only two commands are implemented: start and stop.
> Add LSP tester code

- Makefile
- source/spawn/spawn-posix.ads
- source/spawn/spawn-processes-monitor.adb
- source/spawn/spawn-processes.adb
- source/spawn/spawn-processes.ads
- source/tester/tester-tests.adb
- source/tester/tester-tests.ads
- tester.md
- testsuite/ada_lsp/0002-shutdown.json
Add new command `send` to send request to LSP server and wait response.
> New command for tester

- gnat/lsp.gpr
- source/ada/lsp-ada_contexts.adb
- source/ada/lsp-ada_documents.adb
- source/protocol/lsp-json_streams.adb
- source/protocol/lsp-messages.adb
- source/server/lsp-servers-handlers.adb
- source/server/lsp-servers.adb
reorder subprogram bodies in alphabetical order and add `-gnatyo` option
> Style improvement

- source/ada/lsp-ada_contexts.adb
I've switch directory and file name by mistake
> Fix project file loading.

- Makefile
- testsuite/ada_lsp/0001-start_stop/test.yaml
- testsuite/ada_lsp/0002-shutdown/test.yaml
- testsuite/ada_lsp/0003-get_symbols/test.yaml
- testsuite/ada_lsp/def_name/test.yaml
- testsuite/ada_lsp/find_all_refs/find_all_refs.json
- testsuite/ada_lsp/find_all_refs/test.yaml
- testsuite/ada_lsp/project_config/test.yaml
- testsuite/ada_lsp/project_search/test.yaml
- testsuite/drivers/__init__.py
- testsuite/drivers/basic.py
- testsuite/run-tests
- testsuite/run.sh
- testsuite/testsuite.py
For integration in the AdaCore testing system.
> Add an e3-based testsuite driver for the ALS

- Makefile
- testsuite/drivers/basic.py
And a mode for the test driver to run without having to see the build tree.
> Add a mode for static builds

- Makefile
Allows overriding previous installs.
> Call gprinstall with -f

- README.md
- source/protocol/lsp.ads
- source/server/lsp-servers.adb
And document their activation in README.md.
> Add traces for logging all input/output

- scripts/json_transformations.py
- scripts/replay.py
And add some code ready to transform traces files to
our json format for tests.
> S329-029 add a converter from test traces to protocol string

- source/ada/lsp-ada_contexts.adb
- source/ada/lsp-ada_contexts.ads
- source/ada/lsp-ada_handlers.adb
- testsuite/ada_lsp/find_all_refs_subp/main.c
- testsuite/ada_lsp/find_all_refs_subp/p.gpr
- testsuite/drivers/convert_test.sh
And enhance a test to check for this.
> S404-051 Fix "find all references" for multi-language projects

- source/ada/lsp-ada_contexts.adb
- source/ada/lsp-ada_contexts.ads
- source/ada/lsp-ada_documents.ads
- source/ada/lsp-ada_handlers.adb
- testsuite/ada_lsp/publish_diag/diag_on_open.json
Change textDocument/didOpen handler to publish diagnostics. Also
chage textDocument/didClose handler to clean diagnostics up.
> S514-005 Publish diagnostics on file open

- source/ada/lsp-ada_contexts.adb
- source/ada/lsp-ada_contexts.ads
- source/ada/lsp-ada_documents.adb
- source/ada/lsp-ada_handlers.adb
And default the charset to iso-8859-1, which is the GNAT default.
> S523-033 add support for reading the charset from the config

- source/uri/uris.adb
Avoids a potential constraint_error depending on where
the ALS was launched from, and simplify the URI conversion
function.
> S531-034 Fix the conversion of URI to file

- README.md
- scripts/generate.py
- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-ada_handlers.ads
- source/client/lsp-clients-response_handlers.ads
- source/client/lsp-clients.adb
- source/client/lsp-clients.ads
- source/protocol/generated/lsp-messages-requests.adb
- source/protocol/generated/lsp-messages-requests.ads
- source/protocol/lsp-messages.adb
- source/protocol/lsp-messages.ads
- testsuite/ada_lsp/type_definition/bbb.adb
- testsuite/ada_lsp/type_definition/bbb.ads
- testsuite/ada_lsp/type_definition/test.yaml
- testsuite/ada_lsp/type_definition/type_definition.json
A basic test has also been added.
> S527-008: Implement the textDocument/typeDefinition request

- source/ada/lsp-ada_contexts.adb
- source/ada/lsp-ada_contexts.ads
- source/ada/lsp-ada_handlers.adb
- testsuite/ada_lsp/S528-037.create_file/aaa.ads
- testsuite/ada_lsp/S528-037.create_file/bbb.adb
- testsuite/ada_lsp/S528-037.create_file/create_file.json
- testsuite/ada_lsp/S528-037.create_file/test.yaml
We also track list of opened files that doesn't belong to the project.
This allows correct work of cross-references for these files.
> S528-037 Recompute project view on didOpen unknown file.

- source/uri/uris.adb
And add a ??? comment to explain this.
This is temporary, to be checked with the GNAT team whether
the changes are expected. In the meantime, unblock the
nightly tests + the CI.
> S531-034 Add a special-case treatment for the new GNAT

- integration/appveyor/appveyor.sh
- integration/travis/Dockerfile
- integration/travis/travis.sh
> S624-023 Use stable libadalang branch to build ALS

- source/ada/lsp-ada_contexts.adb
- source/ada/lsp-ada_contexts.ads
- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-lal_utils.adb
- source/ada/lsp-lal_utils.ads
- testsuite/ada_lsp/called_by_not_open/called_by_not_open.json
- testsuite/ada_lsp/called_by_not_open/main.adb
- testsuite/ada_lsp/called_by_not_open/p.adb
- testsuite/ada_lsp/called_by_not_open/p.ads
- testsuite/ada_lsp/called_by_not_open/p.gpr
Support the queries textdocument/hover and textdocument/alsCalledBy
on Uris for documents which are not currently open.
Add a test for the alsCalledBy request.
> S618-021 Support queries on non-open documents

- source/ada/lsp-ada_contexts.adb
- source/ada/lsp-ada_contexts.ads
- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-lal_utils.adb
- source/ada/lsp-lal_utils.ads
> Adapt codebase to recent LAL changes.

- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-lal_utils.ads
- testsuite/ada_lsp/called_by.null_subp/called_by.null_subp.json
- testsuite/ada_lsp/called_by.null_subp/main.adb
- testsuite/ada_lsp/called_by.null_subp/p.gpr
- testsuite/ada_lsp/called_by.null_subp/pack.ads
- testsuite/ada_lsp/called_by.null_subp/test.yaml
And add a test for this feature.
> S703-022 Add support for querying alsCalledBy on a null subprogram

- source/ada/lsp-ada_contexts.adb
- source/ada/lsp-ada_documents.adb
- source/ada/lsp-ada_documents.ads
- testsuite/ada_lsp/project_reload/choices.gpr
- testsuite/ada_lsp/project_reload/project_reload.json
- testsuite/ada_lsp/project_reload/second.adb
- testsuite/ada_lsp/project_reload/test.yaml
- testsuite/ada_lsp/project_reload/third.adb
- testsuite/ada_lsp/project_reload/to_be_called.adb
after each update of Libadalang Context. Otherwise LSP_Document
references outdated Analisys_Unit and some requests fail.
> S702-042 Update all stored Analisys_Units

- source/spawn/spawn-posix.ads
- source/spawn/spawn-processes__posix.adb
As discussed in the ticket it could happen sometimes.
> S709-021 Restart I/O operation on EINTR.

- source/client/lsp-clients.adb
- source/client/lsp-clients.ads
Follow-up from the previous refactoring.
> Remove Client code for handling log/message notifications

- source/ada/lsp-ada_driver.adb
... to specify the location of the traces file.
Also add a --help switch.
> S808-017 Add support for a --tracefile switch

- source/ada/lsp-ada_contexts.adb
- source/ada/lsp-ada_contexts.ads
- source/ada/lsp-ada_documents.adb
- source/ada/lsp-ada_handlers.adb
Cleanup a few APIs, removing parameters where it isn't needed.
> S815-010 Minor reformatting

- scripts/traces_to_test.py
Minor enhancement to ease the creation of tests from GPS logs.
> Allow passing the traces traces_to_test.py

- testsuite/ada_lsp/called_by/called_by.json
- testsuite/ada_lsp/called_by_not_open/called_by_not_open.json
The new version of LAL is more precise in determining the
canonical declaration of a task.
> Adjust test baseline

- source/ada/lsp-ada_handlers.adb
> S815-010 Do not report error messages when loading the default project

- source/ada/lsp-lal_utils.adb
- testsuite/ada_lsp/rename/default.gpr
- testsuite/ada_lsp/rename/main.adb
- testsuite/ada_lsp/rename/rename.json
Don't report name resolution as imprecise if we already has
defining_name.
Don't report it neither if name resolution fails.
> S820-009 Fix detection of imprecise name resolving

- source/ada/lsp-ada_contexts.adb
- source/ada/lsp-ada_contexts.ads
- source/ada/lsp-lal_utils.adb
Rather than using a call to P_Find_All_References, use the
P_Is_Called_By API.
> S907-001 Reimplement "is called by" with the right API

- testsuite/drivers/gnatcov.py
This PR is ready to be reviewed, but please let me merge it, as the merge needs to happen on the same day the corresponding GNATcoverage commit gets in. Thanks!
> Update after GNATcoverage's renaming for ISI files (to SID)

- source/ada/lsp-ada_contexts.adb
- source/ada/lsp-ada_contexts.ads
- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-lal_utils.adb
- source/ada/lsp-lal_utils.ads
This PR is ready to be reviewed, but please don’t merge it: it depends on changes from Libadalang’s `master` branch. I’ll take care of merging it once the `stable` branch is bumped. Thanks!
> Rename Is_Called_By to Find_All_Calls

- integration/vscode/ada/package.json
Hello,
I was about to create an Ada language support extension for Visual Studio Code when I discovered your repo and I thing you are on the right way by using the Language Server Protocol.
I would love to contribute to your work with this first pull request, adding a problem matcher for this extension.
Would it be possible to integrate it an push a new version of the Visual Studio Extension onto its marketplace ?
Thanks a lot.
Kind regard,
Denis Gautherot.
> [enh] Add Problem Matcher

- source/ada/lsp-ada_documents.adb
> Fix completion in the middle of an ID that is part of a DottedName

- source/ada/lsp-lal_utils.adb
Found while working on S813-025
> Check for node nullity in fallback mechanism

- source/ada/lsp-ada_contexts.ads
- source/protocol/lsp-messages.adb
- source/uri/uris.adb
Fix an uninitialized variable found by valgrind.
Fix a redundant test flagged by CodePeer.
Fix typos.
> SC06-071 Minor fixes

- scripts/traces_to_test.py
- testsuite/testsuite.py
Fix typo.
Fix traces_to_test.py: assume the directory is already created.
> Minor edits

- source/ada/lsp-ada_handlers.adb
- testsuite/ada_lsp/C825-005.xrefs.extending/test.json
- testsuite/ada_lsp/D301-004.xrefs.generics/test.json
- testsuite/ada_lsp/D803-003.xrefs.generics_go_to_body/test.json
- testsuite/ada_lsp/F131-024.xrefs.separate_body/test.json
- testsuite/ada_lsp/F222-029.xrefs.prefixed_notation/test.json
- testsuite/ada_lsp/G323-009.tooltips.function_prototype/test.json
- testsuite/ada_lsp/JB24-033.xrefs.no_refs_for_non_loaded_projects/test.json
- testsuite/ada_lsp/O208-003.xrefs.aggregate_library_projects/test.json
- testsuite/ada_lsp/P107-003.refactoring.underscores/test.json
- testsuite/ada_lsp/P429-023.refactoring.rename_clauses/test.json
- testsuite/ada_lsp/QB01-002.xrefs.non_ascii_documentation/test.json
- testsuite/ada_lsp/S820-016.called_by.entry/test.json
- testsuite/ada_lsp/SA11-040.definition.fallback/test.json
- testsuite/ada_lsp/SA22-029.rename_in_comments/test.json
- testsuite/ada_lsp/SA24-055.called_by_on_abstract/test.json
- testsuite/ada_lsp/aggregate.references_after_update/test.json
- testsuite/ada_lsp/aggregate.simple/test.json
- testsuite/ada_lsp/called_by.null_subp/called_by.null_subp.json
- testsuite/ada_lsp/called_by_dispatching/test.json
- testsuite/ada_lsp/callgraph.named_blocks/test.json
- testsuite/ada_lsp/definition_and_overridings/test.json
- testsuite/ada_lsp/indexing_progress/test.json
- testsuite/ada_lsp/invalidation.file_contents/test.json
- testsuite/ada_lsp/rename.not_up_to_date/test.json
- testsuite/ada_lsp/rename/rename.json
> SA17-041-1 Send renameProvider=true in initialization response.

- integration/travis/travis.sh
Tentative to understand the download issue.
> Make the output of wget more verbose

- source/ada/lsp-ada_contexts.adb
- source/ada/lsp-ada_contexts.ads
- source/ada/lsp-ada_driver.adb
- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-ada_handlers.ads
- source/server/lsp-servers.adb
- source/tester/tester-tests.adb
The Message_Handler now owns the project tree and project environment.
Add various missing calls to free data structures.
Increase the wait times for snippets, as a tentative to stabilize
CI builders.
> SC12-037 Fix memory leaks

- source/ada/lsp-ada_handlers.adb
The "implicit project" mechanism is buggy and has an inconvenient
behavior: work around these by using an "empty project" instead.
> SC24-041 Fix loading of default projects under Windows

- source/ada/lsp-ada_documents.adb
- source/ada/lsp-ada_documents.ads
- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-ada_handlers.ads
- source/protocol/lsp-messages.adb
- source/server/lsp-message_loggers.adb
- testsuite/ada_lsp/get_symbol_hier/aaa.ads
- testsuite/ada_lsp/get_symbol_hier/test.json
- testsuite/ada_lsp/get_symbol_hier/test.yaml
if client has corresponding capability. For SA21-029.
> SC27-004 Return hierarchical document symbols

- testsuite/drivers/gnatcov.py
Hello,
Note that the corresponding change in GNATcoverage is not merged yet, so please let me merge this one so that I can merge both in sync. Thanks in advance!
> Update testsuite to the new gnatcov interface

- testsuite/leaks.supp
- testsuite/testsuite.py
In addition to memory validity, checks, valgrind now reports
memory leaks.
> SC06-071 activate valgrind leak checks

- source/ada/lsp-ada_context_sets.adb
- source/ada/lsp-ada_context_sets.ads
- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-ada_handlers.ads
Create Ada_Context_Sets package and move some function
from Ada_Handlers into it. This make Ada_Handlers a bit
shorter and introduces an abstraction for context container.
> SC28-001 Minor refactoring

- source/ada/lsp-ada_handlers.adb
In the case of incremental text synchronization, slightly adjust
the behavior for skipping change notifications when there
are several notifications in the queue for the same document.
> T123-048 Fix text synchronization issue

- source/ada/lsp-ada_documents.ads
- source/ada/lsp-ada_driver.adb
- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-ada_handlers.ads
- source/ada/lsp-error_decorators.adb
- source/ada/lsp-error_decorators.ads
- source/ada/lsp-fuzz_decorators.adb
- source/ada/lsp-fuzz_decorators.ads
- source/server/lsp-servers.adb
- source/server/lsp-servers.ads
- testsuite/ada_lsp/called_by_dispatching/test.json
Add a fuzzing decorator, and a capacity for detecting document inconsistencies based on this fuzzing decorator.
> T202-005 Initial support for fuzzing

- source/ada/lsp-fuzz_decorators.adb
This can be used to create stress-tests for the text
synchronization feature.
> T123-048 Add a mode to live-check incremental text synchronization

- source/ada/lsp-ada_handlers.adb
- testsuite/ada_lsp/named_params/test.json
whe cursor on the function name of some subprogram call.
> SC28-001 Trigger Named_Parameters refactoring

- .editorconfig
I sampled about 14 files in different directories and came up with this for general rules. Seems like you guys have some python specific rules, but I don't know python.
> Added basic .editorconfig, closes #334

- integration/vscode/ada/ada-snippets.json
- integration/vscode/ada/gpr-snippets.json
- integration/vscode/ada/package.json
- integration/vscode/ada/syntaxes/ada.tmLanguage.json
- integration/vscode/ada/syntaxes/ali.tmLanguage.json
**Don't merge this yet**
I'm opening the PR now to allow for individual components to be assessed and merged/rejected much easier than if the entire thing was done all at once. There's several conflicting files, such as the ada/gpr definitions, but also several new files, and different naming schemes for things, that will all need to be addressed.
As stated in #309, part of why I'm doing this is that I simply can't continue to use VS Code given how parts of a disability has progressed, and how the VS Code team doesn't seem interested in a solution, which is insane because I know I'm not the only person troubled by use of a mouse.
The files I'm merging are from the last state of the repo that made it up on the marketplace. I've worked out better solutions for the overall approach and …
> Merging Projects

- source/protocol/lsp-messages.adb
> SC28-001 Fix Document_Change reading

- scripts/digest_traces.py
For the purpose of debugging and investigating memory issues.
> T210-007 Add a script which digests traces

- source/ada/lsp-ada_handlers.adb
- testsuite/ada_lsp/implementation.aggregates/test.json
- testsuite/ada_lsp/implementation.overridings/test.json
- testsuite/ada_lsp/implementation/test.json
in the initialization response.
> T226-034 Announce implementationProvider

- integration/vscode/ada/syntaxes/ada.tmLanguage.json
Created `library_unit` as a new top level class. Added in `package_body`, `package_spec` and `subprogram_body`. Currently the older `subroutine` is still present as I need to flatten that completely, but it's complicated.
> Library unit

- README.md
- integration/vscode/ada/.editorconfig
- integration/vscode/ada/syntaxes/ada.tmLanguage.json
- integration/vscode/ada/syntaxes/ali.tmLanguage.json
- integration/vscode/ada/syntaxes/gpr.tmLanguage.json
Normalized indentation since it was getting mixed. Added an `.editorconfig` to the `vscode/ada/` dir with some specifics for that directory.
> Normalized indentation

- source/ada/lsp-ada_handlers-named_parameters_commands.adb
- testsuite/ada_lsp/named_params/test.adb
- testsuite/ada_lsp/named_params/test.json
for cases with absent optional arguments.
> T302-034 Fix named params refactoring

- source/ada/lsp-ada_documents.adb
This allows to return much less results, increasing the
overall performance for this request.
> T311-014: Filter completion results with typed prefix

- source/ada/lsp-ada_documents.adb
- testsuite/ada_lsp/SA22-032.folding/main.adb
- testsuite/ada_lsp/SA22-032.folding/test.json
- don't process Ada_Subp_Spec, it is a part of Ada_Subp_Decl
- don't process Ada_Aspect_Assoc_List and Ada_Aspect_Assoc:
parts of Ada_Aspect_Spec
> SA22-032 Corrections for the code folding

- README.md
- integration/vscode/ada/package.json
> SA09-033 Add deprecation message as we move to a new account

- source/ada/lsp-ada_handlers.adb
- testsuite/ada_lsp/aggregate.is_called_by/agg.gpr
- testsuite/ada_lsp/aggregate.is_called_by/common/common.gpr
- testsuite/ada_lsp/aggregate.is_called_by/common/common_pack.adb
- testsuite/ada_lsp/aggregate.is_called_by/common/common_pack.ads
- testsuite/ada_lsp/aggregate.is_called_by/p/main.adb
- testsuite/ada_lsp/aggregate.is_called_by/p/p.gpr
- testsuite/ada_lsp/aggregate.is_called_by/q/main.adb
- testsuite/ada_lsp/aggregate.is_called_by/q/q.gpr
- testsuite/ada_lsp/aggregate.is_called_by/test.json
- testsuite/ada_lsp/aggregate.is_called_by/test.yaml
Duplicates were happening when concatening the results from
different contexts.
Add a test.
> T317-049: Remove duplicate results in Is_Called_By request

- scripts/generate.py
- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-ada_handlers.ads
- source/ada/lsp-error_decorators.adb
- source/ada/lsp-error_decorators.ads
- source/protocol/generated/lsp-messages-server_requests.adb
- source/protocol/generated/lsp-messages-server_requests.ads
- source/protocol/generated/lsp-server_request_receivers.ads
- source/protocol/lsp-messages-server_responses.adb
- source/protocol/lsp-messages-server_responses.ads
- source/protocol/lsp-messages.adb
- source/protocol/lsp-messages.ads
- source/protocol/lsp-server_response_senders.ads
- source/server/generated/lsp-server_request_handlers.ads
- source/server/generated/lsp-servers-handle_request.adb
- source/server/lsp-message_loggers.adb
- source/server/lsp-message_loggers.ads
to complete migration to LSP 3.15.
> T212-025 Add SelectionRange request

- source/ada/lsp-ada_documents.adb
- source/ada/lsp-ada_documents.ads
- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-ada_handlers.ads
- source/protocol/lsp-messages.adb
- source/protocol/lsp-messages.ads
- testsuite/ada_lsp/0003-get_symbols/0003-get_symbols.json
- testsuite/ada_lsp/get_symbol_hier/test.json
Various enhancements/fixes to adapt the Document_Symbols request for the GS outline
> Topic/sa21 029.document symbols.outline

- source/ada/lsp-ada_handlers-named_parameters_commands.adb
- testsuite/ada_lsp/named_params.dot_calls/default.gpr
- testsuite/ada_lsp/named_params.dot_calls/src/bar.ads
- testsuite/ada_lsp/named_params.dot_calls/src/main.adb
- testsuite/ada_lsp/named_params.dot_calls/test.json
- testsuite/ada_lsp/named_params.dot_calls/test.yaml
An automatic test has been added too.
> T401-049: Fix named parameters command for dot calls

- source/client/lsp-raw_clients.adb
- source/client/lsp-raw_clients.ads
> SA17-041 Raw_Client.Raw_Client has been added.

- source/ada/lsp-ada_documents.adb
- source/protocol/lsp-messages.adb
- source/protocol/lsp-messages.ads
- testsuite/ada_lsp/SA21-029.documentSymbol.function/foo.adb
- testsuite/ada_lsp/SA21-029.documentSymbol.function/test.json
- testsuite/ada_lsp/SA21-029.documentSymbol.function/test.yaml
- testsuite/ada_lsp/SA21-029.documentSymbol.with/test.json
- testsuite/ada_lsp/get_symbol_hier/test.json
Separate procedure and function.
Separate type and structure.
> SA21-029: Refine documentSymbol kinds

- integration/vscode/ada/CONTRIBUTING.md
Describes how the extension's classifier works, defines some terminology, and suggests how to contribute.
> Added VS Code specific CONTRIBUTING.md

- source/protocol/lsp-types.adb
othervise we get Storage_Error when the stack is exhausted.
> T414-024 Avoid large sting on the stack

- integration/vscode/ada/syntaxes/ada.tmLanguage.json
This PR adds features requested in #412. It may introduce conflicts with PR #411.
* Resolve bugs in syntax highlighting
* Adding procedure calls
> Improve support for syntax highlighting

- integration/vscode/ada/syntaxes/ada.tmLanguage.json
This fixes the out-of-order issue that was created with the `repository`. It seems like because the previous fixes were part of a different PR with other things going on at the same time, git failed to merge correctly and wound up with duplicate entries, as well as entries in unintended places. Everything was correct and still worked, this is just code cleanliness improvements.
> Reorganization

- integration/vscode/ada/syntaxes/ada.tmLanguage.json
- integration/vscode/ada/testsuite_grammar/nesting/main.adb.snap
- integration/vscode/ada/testsuite_grammar/types/types.ads
- integration/vscode/ada/testsuite_grammar/types/types.ads.snap
*This is a work in progress.*
I have added almost all the constructions that were missing.
The highlighter is much more flexible than the previous one.
I put it here if someone wants to test. Also I'm planing to supply more tests.
It works rather well with correct Ada code, and more or less well with incorrect code.
There are still some cases that need to be improved and probably bugs to solve on my code.
#436
> Improve highlighter

- source/ada/lsp-ada_documents.adb
- source/ada/lsp-ada_documents.ads
- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-ada_handlers.ads
- testsuite/ada_lsp/T409-045.comments_folding/main.adb
- testsuite/ada_lsp/T409-045.comments_folding/p.gpr
- testsuite/ada_lsp/T409-045.comments_folding/test.json
- testsuite/ada_lsp/T409-045.comments_folding/test.yaml
Do not send information about comment blocks when this switch
is False.
> T409-045 foldComment setting for the textDocument/foldingRange

- source/ada/lsp-ada_driver.adb
to have less warnings from the Valgrind.
> T610-025 Destroy the secondary stack

- source/ada/lsp-common.adb
- testsuite/ada_lsp/hover.for_loops/main.adb
- testsuite/ada_lsp/hover.for_loops/test.json
- testsuite/ada_lsp/hover.for_loops/test.yaml
> T625-016: Fix textDocument/hover hander for loop iterators

- source/ada/lsp-ada_contexts.adb
- source/ada/lsp-ada_contexts.ads
- source/ada/lsp-ada_documents.adb
- source/ada/lsp-ada_documents.ads
- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-ada_handlers.ads
- source/protocol/lsp-messages.ads
- testsuite/ada_lsp/T623-017.format_uses_project/default.gpr
- testsuite/ada_lsp/T623-017.format_uses_project/main.adb
- testsuite/ada_lsp/T623-017.format_uses_project/test.json
- testsuite/ada_lsp/T623-017.format_uses_project/test.yaml
to keep Pretty_Printer switches from a project file
for document formatting request.
> T623-017 Use per context gnatpp command line object

- source/ada/lsp-ada_documents.adb
- testsuite/ada_lsp/completion.complex_renames/test.json
- testsuite/ada_lsp/completion.end_labels/test.json
- testsuite/ada_lsp/completion.subp_parameters/test.json
- testsuite/ada_lsp/completion.subp_params_dotted_names/test.json
... and remove unnecessary traces when getting the doc.
> T706-006: Add location to completion items doc

- source/ada/lsp-ada_contexts.adb
- source/ada/lsp-ada_contexts.ads
- source/ada/lsp-ada_handlers.adb
- testsuite/ada_lsp/completion.end_labels/test.json
- testsuite/ada_lsp/indexing_progress/hello.adb
- testsuite/ada_lsp/indexing_progress/hello2.adb
- testsuite/ada_lsp/indexing_progress/hello3.adb
- testsuite/ada_lsp/indexing_progress/hello4.adb
- testsuite/ada_lsp/indexing_progress/p.gpr
- testsuite/ada_lsp/indexing_progress/test.json
- testsuite/ada_lsp/indexing_progress/test.yaml
Reverts AdaCore/ada_language_server#479
Until T707-019 is fixed.
> Revert "T623-024: Index runtime files at startup"

- source/spawn/spawn-internal__glib_windows.ads
- source/spawn/spawn-internal__windows.ads
- source/spawn/spawn-processes-windows.adb
- source/spawn/spawn-processes__glib_windows.adb
> T710-023 Fix size of data to be submitted.

- testsuite/testsuite.py
Remove class attributes that are no longer needed.
> T707-058 cleanup in the testsuite driver

- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-lal_utils.adb
- source/ada/lsp-lal_utils.ads
Extract List_Bodies_Of to LSP.Lal_Utils.
> T714-019 Code organization

- source/ada/lsp-lal_utils.ads
- testsuite/ada_lsp/T709-018.is_called_by.name_collision/common.ads
- testsuite/ada_lsp/T709-018.is_called_by.name_collision/foo.adb
- testsuite/ada_lsp/T709-018.is_called_by.name_collision/pack1.adb
- testsuite/ada_lsp/T709-018.is_called_by.name_collision/pack1.ads
- testsuite/ada_lsp/T709-018.is_called_by.name_collision/pack2.adb
- testsuite/ada_lsp/T709-018.is_called_by.name_collision/pack2.ads
- testsuite/ada_lsp/T709-018.is_called_by.name_collision/test.gpr
- testsuite/ada_lsp/T709-018.is_called_by.name_collision/test.json
- testsuite/ada_lsp/T709-018.is_called_by.name_collision/test.yaml
Work around the naive implementation of Ordered_Maps.
Add a test.
> T709-018: naming collision in is_called_by

- testsuite/run-tests
Fixes issues in environments mixing gnatpython and e3
> T717-032 Make run-tests python3 only

- doc/README.md
- doc/called_by.md
- doc/calls.md
- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-ada_handlers.ads
- source/ada/lsp-error_decorators.adb
- source/ada/lsp-error_decorators.ads
- source/ada/lsp-lal_utils.adb
- source/ada/lsp-lal_utils.ads
- source/protocol/generated/lsp-message_io.adb
- source/protocol/generated/lsp-messages-server_requests.adb
- source/protocol/generated/lsp-messages-server_requests.ads
- source/protocol/generated/lsp-server_request_receivers.ads
- source/protocol/lsp-messages-server_responses.adb
- source/protocol/lsp-messages-server_responses.ads
- source/protocol/lsp-messages.ads
- source/protocol/lsp-server_response_senders.ads
- source/server/generated/lsp-server_request_handlers.ads
- source/server/generated/lsp-servers-handle_request.adb
- source/server/lsp-message_loggers.adb
- source/server/lsp-message_loggers.ads
- testsuite/ada_lsp/calls/calls.json
- testsuite/ada_lsp/calls/main.adb
- testsuite/ada_lsp/calls/p.adb
- testsuite/ada_lsp/calls/p.ads
- testsuite/ada_lsp/calls/p.gpr
- testsuite/ada_lsp/calls/test.yaml
Support for tasks missing due to bug in libadalang [T716-049].
CalledBy request documentation typos fixed.
Add documentation for ALS Calls request.
Add a test for ALS Calls request.
> SC27-003 Implement ALS Calls Request

- source/ada/lsp-ada_completion_sets.adb
- source/ada/lsp-ada_completion_sets.ads
- testsuite/ada_lsp/completion.invisible2/bar.ads
- testsuite/ada_lsp/completion.invisible2/default.gpr
- testsuite/ada_lsp/completion.invisible2/main.adb
- testsuite/ada_lsp/completion.invisible2/test.json
- testsuite/ada_lsp/completion.invisible2/test.yaml
in global name cache as workaround of an issue from T806_020
> T805-014 Replace Defining_Name equality operator

- source/ada/lsp-ada_documents.adb
- source/ada/lsp-ada_documents.ads
introduced in invisible symbol completion.
> T805-014 Fix uninitialized result value

- source/ada/lsp-ada_documents.adb
- testsuite/ada_lsp/completion.defining_names/main.adb
- testsuite/ada_lsp/completion.defining_names/test.json
- testsuite/ada_lsp/completion.defining_names/test.yaml
An automatic has also been added.
> T728-019: Don't propose completion when defining new symbols

- source/ada/lsp-lal_utils.adb
The Imprecise Fallback was unable to match a body and a spec
defined at the same line number (in 2 different files).
> T812-022: Improve Imprecise Fallback

- source/client/lsp-clients-response_handlers.ads
- source/client/lsp-clients.adb
- source/client/lsp-clients.ads
Please don't commit it, need to synchronize with GS code
> T826-031 Allow to generate custom request identifiers.

- source/ada/lsp-ada_driver.adb
- source/ada/lsp-ada_handlers-refactor_imports_commands.adb
- source/ada/lsp-ada_handlers-refactor_imports_commands.ads
- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-ada_handlers.ads
- testsuite/ada_lsp/SA22-032.folding/test.json
- testsuite/ada_lsp/completion.aggregates.derived_types/test.json
- testsuite/ada_lsp/completion.aggregates.simple/test.json
- testsuite/ada_lsp/completion.complex_renames/test.json
- testsuite/ada_lsp/completion.defining_names/test.json
- testsuite/ada_lsp/completion.end_labels/test.json
- testsuite/ada_lsp/completion.keywords/test.json
- testsuite/ada_lsp/completion.no_snippet_for_params/test.json
- testsuite/ada_lsp/completion.subp_parameters/test.json
- testsuite/ada_lsp/completion.subp_params_dotted_names/test.json
- testsuite/ada_lsp/hover.for_loops/test.json
- testsuite/ada_lsp/named_params.dot_calls/test.json
- testsuite/ada_lsp/named_params/test.json
- testsuite/ada_lsp/refactor_imports_commands/a.adb
- testsuite/ada_lsp/refactor_imports_commands/a.ads
- testsuite/ada_lsp/refactor_imports_commands/default.gpr
- testsuite/ada_lsp/refactor_imports_commands/e.ads
- testsuite/ada_lsp/refactor_imports_commands/main.adb
- testsuite/ada_lsp/refactor_imports_commands/refactor_imports_commands.json
- testsuite/ada_lsp/refactor_imports_commands/rts-empty/adainclude/ada.ads
- testsuite/ada_lsp/refactor_imports_commands/rts-empty/adainclude/system.ads
- testsuite/ada_lsp/refactor_imports_commands/test.yaml
- testsuite/ada_lsp/show_dependencies.aggregate/test.json
- testsuite/ada_lsp/show_dependencies/test.json
New codeAction command and handler to perform refactoring of
"with" clauses and prefixes.
Test case to prove that the protocol messages are correct. Therefore,
the test project has an empty runtime so that the test runs faster.
> T722-025 LAL Tools Refactor Imports Integration

- README.md
- doc/settings.md
- doc/traces.md
- integration/travis/deploy.sh
- integration/vscode/Code Samples/.vscode/extensions.json
- integration/vscode/Code Samples/.vscode/launch.json
- integration/vscode/Code Samples/.vscode/tasks.json
- integration/vscode/Code Samples/README.md
- integration/vscode/Code Samples/hello.adb
- integration/vscode/Code Samples/hello.gpr
- integration/vscode/ada/README.md
Provide a Code Sample with build and debug tasks configured.
Add a document for supported traces and another one for settings.
Refs #528 and #468.
> Update README.md in root folder and in VS Code extension.

- source/ada/lsp-ada_documents.adb
- testsuite/ada_lsp/T827-018.documentSymbol.pragma/foo.adb
- testsuite/ada_lsp/T827-018.documentSymbol.pragma/test.gpr
- testsuite/ada_lsp/T827-018.documentSymbol.pragma/test.json
- testsuite/ada_lsp/T827-018.documentSymbol.pragma/test.yaml
> T827-018: Show high level pragma in documentSymbols

- source/ada/lsp-ada_contexts.adb
- source/ada/lsp-ada_contexts.ads
- source/ada/lsp-ada_handlers.adb
- testsuite/ada_lsp/declaration.overridings_on_usage/class_definition.adb
- testsuite/ada_lsp/declaration.overridings_on_usage/class_definition.ads
- testsuite/ada_lsp/declaration.overridings_on_usage/class_definition.subclass.adb
- testsuite/ada_lsp/declaration.overridings_on_usage/class_definition.subclass.ads
- testsuite/ada_lsp/declaration.overridings_on_usage/default.gpr
- testsuite/ada_lsp/declaration.overridings_on_usage/gb.adb
- testsuite/ada_lsp/declaration.overridings_on_usage/test.json
- testsuite/ada_lsp/declaration.overridings_on_usage/test.yaml
- testsuite/ada_lsp/declaration.overridings_on_usage/user.adb
- testsuite/ada_lsp/declaration.overridings_on_usage/user.ads
We now take into account the alsDisplayMethodAncestryOnNavigation flag
properly.
> T122-009: Fix textDocument/declaration behavior

- README.md
- doc/HACKING.md
- integration/vscode/ada/package.json
to match numeration with master branch of the GNAT Studio.
> Change default version from 21 to 22

- source/ada/lsp-ada_documents.adb
The LCS algorithm generates a diff between lines: it will return
a wrong result if the buffer doesn't finish by a EOL symbol.
=> Add a defensive function to set all the wrong location to
the end of the buffer.
> T928-015: Sanitize the result of the LCS algorithm

- testsuite/ada_lsp/T928-015.formatting.end_of_buffer/default.gpr
- testsuite/ada_lsp/T928-015.formatting.end_of_buffer/test.json
- testsuite/ada_lsp/T928-015.formatting.end_of_buffer/test.yaml
- testsuite/ada_lsp/T928-015.formatting.end_of_buffer/ui.ads
> Topic/t928 015.diff.end of buffer

- testsuite/testsuite.py
Found during TA26-023 investigation
> Check for file with ".exe" extension to find executables on Windows.

- source/server/lsp-servers.adb
Turn it off by default for now.
> TA09-019 Add a trace to control filesystem monitoring

- source/ada/lsp-ada_handlers-named_parameters_commands.adb
- source/ada/lsp-ada_handlers.adb
- testsuite/ada_lsp/TB12-017.named.parameters.0/TB12-017.named.parameters.0.json
- testsuite/ada_lsp/TB12-017.named.parameters.0/default.gpr
- testsuite/ada_lsp/TB12-017.named.parameters.0/src/foo.adb
- testsuite/ada_lsp/TB12-017.named.parameters.0/src/foo.ads
- testsuite/ada_lsp/TB12-017.named.parameters.0/src/main.adb
- testsuite/ada_lsp/TB12-017.named.parameters.0/test.yaml
- testsuite/ada_lsp/TB12-017.named.parameters.1/TB12-017.named.parameters.1.json
- testsuite/ada_lsp/TB12-017.named.parameters.1/default.gpr
- testsuite/ada_lsp/TB12-017.named.parameters.1/src/foo.adb
- testsuite/ada_lsp/TB12-017.named.parameters.1/src/foo.ads
- testsuite/ada_lsp/TB12-017.named.parameters.1/src/main.adb
- testsuite/ada_lsp/TB12-017.named.parameters.1/test.yaml
- testsuite/ada_lsp/TB12-017.named.parameters.2/TB12-017.named.parameters.2.json
- testsuite/ada_lsp/TB12-017.named.parameters.2/default.gpr
- testsuite/ada_lsp/TB12-017.named.parameters.2/src/foo.adb
- testsuite/ada_lsp/TB12-017.named.parameters.2/src/foo.ads
- testsuite/ada_lsp/TB12-017.named.parameters.2/src/main.adb
- testsuite/ada_lsp/TB12-017.named.parameters.2/test.yaml
Avoid raising exceptions when name parameters is used in invalid places.
> TB12-017: Defensive code for name parameters

- README.md
- scripts/generate.py
- source/ada/lsp-ada_contexts.adb
- source/ada/lsp-ada_documents.adb
- source/ada/lsp-ada_documents.ads
- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-lal_utils.adb
- source/ada/lsp-lal_utils.ads
- source/protocol/generated/lsp-messages-server_requests.adb
- testsuite/ada_lsp/document_highlight/main.adb
- testsuite/ada_lsp/document_highlight/test.json
- testsuite/ada_lsp/document_highlight/test.yaml
A basic test has also been added.
> R306-004: Add implementation for textDocument/highlight

- source/server/lsp-servers.adb
> Update ALS souces after renaming of Each_Stream_Element

- source/ada/lsp-ada_contexts.adb
- testsuite/ada_lsp/called_by.renames/main.adb
- testsuite/ada_lsp/called_by.renames/test.json
- testsuite/ada_lsp/called_by.renames/test.yaml
> TB19-024: Follow rename clauses in Find_All_Calls

- source/ada/lsp-ada_documents.adb
Reverts AdaCore/ada_language_server#604
> Revert "T218-020: Use iterators for completion results."

- source/ada/lsp-ada_handlers.adb
- testsuite/ada_lsp/U121-013.enum_references/hello.gpr
- testsuite/ada_lsp/U121-013.enum_references/main.adb
- testsuite/ada_lsp/U121-013.enum_references/test.json
- testsuite/ada_lsp/U121-013.enum_references/test.yaml
Adding this kind in addition to 'call' when returns result
for 'Find all references'
> U121-013 Add 'reference' kind to enumeration literals

- source/ada/lsp-ada_driver.adb
> Add `--version` command line option

- source/server/lsp-servers.adb
Catch Predicondition_Failure in the same way we intercept
Property_Error, ie assuming that this can happen in the normal
flow when working on invalid code, and not report them to the
IDE.
Systematically store the symbolic backtrace of exceptions in the
log.
Factorize the code to do this for both notifications and requests.
> U308-004 U305-040 Minor update on exception handling

- .github/workflows/build-binaries.yml
- .github/workflows/pack-binaries.sh
> Publish .vsix on the https://open-vsx.org/

- source/ada/lsp-error_decorators.adb
- source/server/lsp-servers.adb
Add code to send an empty response when the exception is due
to "invalid Ada": we don't want to send a backtrace in this case,
but clients are still interested to get the response to the request.
> U308-004 When receiving an exception, always send a response

- .gitpod.Dockerfile
- Makefile
- testsuite/run.sh
Speeds up the testsuite significantly.
> Import e3 in the development environment

- scripts/predefined_completion.py
- source/ada/generated/lsp-predefined_completion-ada2012.ads
... in lsp-predefined_completion-ada2012.ads, in order
to help LAL process the project.
> U317-021 remove big amount of concatenations

- .gitignore
- .gitpod.yml
- doc/gitpod.md
Add subprojects/ to the .gitignore.
Open the welcome message in the editor.
Fix a typo in the welcome message.
> Small changes for gitpod / VS Code integration

- source/ada/lsp-ada_handlers-named_parameters_commands.adb
- source/ada/lsp-ada_handlers.adb
- testsuite/ada_lsp/SC28-001.named.parameters.0/SC28-001.named.parameters.0.json
- testsuite/ada_lsp/SC28-001.named.parameters.0/default.gpr
- testsuite/ada_lsp/SC28-001.named.parameters.0/main.adb
- testsuite/ada_lsp/SC28-001.named.parameters.0/test.yaml
Add Named Parameters to parameters, record components, array elements
and objects that are an access to a subprogram, including anonymous
access.
> SC28-001 Add Named Parameters to access subps

- .vscode/tasks.json
- README.md
- integration/vscode/Code Samples/.vscode/tasks.json
- integration/vscode/ada/.eslintrc.json
- integration/vscode/ada/extension.js
- integration/vscode/ada/gprTaskProvider.js
- integration/vscode/ada/jsconfig.json
- integration/vscode/ada/package.json
auto-detected tasks.
Refs #541
> Add a task provider with "build project"/"check file"

- source/ada/lsp-ada_handlers.adb
- source/protocol/lsp-generic_vectors.adb
- testsuite/ada_lsp/callHierarchy.abstract_subps/main.adb
- testsuite/ada_lsp/callHierarchy.abstract_subps/p.ads
- testsuite/ada_lsp/callHierarchy.abstract_subps/p.gpr
- testsuite/ada_lsp/callHierarchy.abstract_subps/q.ads
- testsuite/ada_lsp/callHierarchy.abstract_subps/test.json
- testsuite/ada_lsp/callHierarchy.abstract_subps/test.yaml
> U415-017: Fix callHierrachy requests for abstract subprograms

- source/ada/lsp-lal_utils.adb
When computing the signatures for a Call_Expr with a closing
parenthesis, then mutliple Error_Stmt nodes can be added.
Ignore then and try to find the Call_Expr in the siblings.
> U427-019: Improve error handling for signatureHelp

- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-lal_utils.adb
- source/ada/lsp-lal_utils.ads
- testsuite/ada_lsp/U429-030.signatureHelp.dot_call/bar.adb
- testsuite/ada_lsp/U429-030.signatureHelp.dot_call/bar.ads
- testsuite/ada_lsp/U429-030.signatureHelp.dot_call/default.gpr
- testsuite/ada_lsp/U429-030.signatureHelp.dot_call/foo.adb
- testsuite/ada_lsp/U429-030.signatureHelp.dot_call/test.json
- testsuite/ada_lsp/U429-030.signatureHelp.dot_call/test.yaml
Handle prefix notation: differentiate between a paremeter prefix
and a package prefix.
Properly select the active parameter + handle designators.
Add a test
> U429-030: Fix signatureHelp active parameter + Prefix notation

- .github/workflows/build-binaries.sh
- .github/workflows/build-binaries.yml
- .gitpod.yml
- README.md
- integration/vscode/ada/README.md
Merge this after libadalang stable binaries uploaded to AWS S3.
> Replace BinTray with AWS S3

- testsuite/ada_lsp/commands.other_file/aaa.adb
- testsuite/ada_lsp/commands.other_file/aaa.ads
- testsuite/ada_lsp/commands.other_file/default.gpr
- testsuite/ada_lsp/commands.other_file/test.json
- testsuite/ada_lsp/commands.other_file/test.yaml
> Add a test for als-other-file command

- testsuite/ada_lsp/U505-017.navigation.fallback/default.gpr
- testsuite/ada_lsp/U505-017.navigation.fallback/src/bar.adb
- testsuite/ada_lsp/U505-017.navigation.fallback/src/bar.ads
- testsuite/ada_lsp/U505-017.navigation.fallback/src/main.adb
- testsuite/ada_lsp/U505-017.navigation.fallback/test.json
- testsuite/ada_lsp/U505-017.navigation.fallback/test.yaml
> U505-017: Add test for navigation fallback

- source/ada/lsp-ada_handlers.adb
> Drop unused entities

- source/ada/lsp-ada_handlers-named_parameters_commands.adb
- source/ada/lsp-ada_handlers-refactor_imports_commands.adb
- source/ada/lsp-lal_utils.adb
- source/ada/lsp-lal_utils.ads
- testsuite/ada_lsp/SC28-001.named.parameters.0/SC28-001.named.parameters.0.json
- testsuite/ada_lsp/U511-009.refactoring.import_with_use/bar.ads
- testsuite/ada_lsp/U511-009.refactoring.import_with_use/default.gpr
- testsuite/ada_lsp/U511-009.refactoring.import_with_use/foo.adb
- testsuite/ada_lsp/U511-009.refactoring.import_with_use/test.json
- testsuite/ada_lsp/U511-009.refactoring.import_with_use/test.yaml
- testsuite/ada_lsp/named_params.dot_calls/test.json
- testsuite/ada_lsp/refactor_imports_commands/refactor_imports_commands.json
Properly check the client capabilities and fix the code handling for
non versioned files.
Use Get_Insert_With_Location.
Add a test.
Adapt test to explicitely set documentChanges
> U511-009: Fix refactoring import capatibility.

- source/ada/lsp-ada_context_sets.adb
- source/ada/lsp-ada_contexts.adb
- source/ada/lsp-ada_contexts.ads
- source/ada/lsp-ada_documents.adb
- source/ada/lsp-ada_documents.ads
- source/ada/lsp-ada_handlers-file_readers.adb
- source/ada/lsp-ada_handlers-other_file_commands.adb
- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-ada_handlers.ads
- source/ada/lsp-fuzz_decorators.adb
- source/ada/lsp-lal_utils.adb
- source/ada/lsp-lal_utils.ads
- source/protocol/lsp-messages.ads
- source/protocol/lsp-types.adb
- source/protocol/lsp-types.ads
- source/server/lsp-message_loggers.adb
- source/server/lsp-servers-fs_watch.adb
> U301-023 Create LSP_URI type and disable "=" for it

- README.md
Extend auto-detected tasks documentation with a short video.
> Add Coc.NVim integration instructions

- integration/vscode/ada/package.json
To fix the failure of the [package](https://github.com/AdaCore/ada_language_server/runs/2990856876?check_suite_focus=true#step:4:267) job of GitHub actions.
> U705-017 Downgrade @types/vscode to engine version

- source/ada/lsp-ada_completions-names.adb
- testsuite/ada_lsp/completion.invisible4/default.gpr
- testsuite/ada_lsp/completion.invisible4/pkg_1-child.ads
- testsuite/ada_lsp/completion.invisible4/pkg_1-child2.ads
- testsuite/ada_lsp/completion.invisible4/pkg_1.ads
- testsuite/ada_lsp/completion.invisible4/test.json
- testsuite/ada_lsp/completion.invisible4/test.yaml
- testsuite/ada_lsp/completion.invisible4/testcomp.adb
to mark invisible completions.
> U622-022 Use Is_Visible libadalang completion property

- Makefile
> U721-004 Force TypeScript compilation for vscode

- source/ada/lsp-ada_contexts.adb
- source/ada/lsp-ada_contexts.ads
- source/ada/lsp-lal_utils.adb
Libadalang.Analysis.P_All_Env_Elements can return multiple times the
same node => do a filtering pass to remove duplicated node.
Also fix a wrong conversion when handling ErrorStmt
> U728-006: Duplicated profile in signatureHelp response

- source/ada/lsp-ada_handlers-named_parameters_commands.adb
- source/ada/lsp-ada_handlers-refactor_change_parameter_mode.adb
- source/ada/lsp-ada_handlers-refactor_imports_commands.adb
- source/ada/lsp-ada_handlers-refactor_move_parameter.adb
- source/ada/lsp-ada_handlers-refactor_remove_parameter.adb
- source/ada/lsp-ada_handlers-refactor_suppress_seperate.adb
This is needed to linked the applyEdit to the codeaction (like
creating messages from the client side)
> U504-030: Set the applyEdit label for codeaction

- source/ada/lsp-common.adb
with Virtual_String method and Virtual_String_Vector.
> U622-021 Replace GNATCOLL.Utils.Split

- source/protocol/lsp-types.adb
- source/server/lsp-message_loggers.adb
> T629-024 Qualify type to prevent build failures.

- source/server/lsp-generic_cancel_check.adb
- source/server/lsp-generic_cancel_check.ads
> T826-026 Add a generic version of Has_Been_Canceled

- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-lal_utils.adb
- source/ada/lsp-lal_utils.ads
- testsuite/ada_lsp/U805-023.signatureHelp.designators/foo.adb
- testsuite/ada_lsp/U805-023.signatureHelp.designators/test.gpr
- testsuite/ada_lsp/U805-023.signatureHelp.designators/test.json
- testsuite/ada_lsp/U805-023.signatureHelp.designators/test.yaml
Previously it was only using the current designator and the
active position.
Add a test.
> U805-023: Filter the signatures using the previous designators

- source/ada/lsp-ada_documents-lal_diagnostics.adb
- source/ada/lsp-ada_documents-lal_diagnostics.ads
- source/ada/lsp-ada_documents.adb
- source/ada/lsp-ada_documents.ads
- source/ada/lsp-ada_handlers-project_diagnostics.adb
- source/ada/lsp-ada_handlers-project_diagnostics.ads
- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-ada_handlers.ads
- source/ada/lsp-diagnostic_sources.ads
- testsuite/ada_lsp/S314-015.refactor_change_parameter_mode_0/test.json
- testsuite/ada_lsp/S314-015.refactor_move_parameter_0/test.json
- testsuite/ada_lsp/S314-015.refactor_remove_parameter_0/test.json
- testsuite/ada_lsp/SC28-001.named.parameters.0/SC28-001.named.parameters.0.json
- testsuite/ada_lsp/T123-048.incremental_editing/test.json
- testsuite/ada_lsp/TB12-017.named.parameters.1/TB12-017.named.parameters.1.json
- testsuite/ada_lsp/U416-030.refactor_change_parameter_mode_0/test.json
- testsuite/ada_lsp/U416-030.refactor_remove_parameter_0/test.json
- testsuite/ada_lsp/U511-009.refactoring.import_with_use/test.json
- testsuite/ada_lsp/U614-038.edits.no_project/test.json
- testsuite/ada_lsp/document_highlight/test.json
- testsuite/ada_lsp/editor.incremental/test.json
- testsuite/ada_lsp/find_all_refs_kinds/find_all_refs_kinds.json
- testsuite/ada_lsp/incorrect_fallback/incorrect_fallback.json
- testsuite/ada_lsp/named_params/test.json
- testsuite/ada_lsp/publish_diag/diag_on_open.json
- testsuite/ada_lsp/publish_diag/publish_diag.json
- testsuite/ada_lsp/refactor_imports_commands/refactor_imports_commands.json
Move Libadalang based diagnostic into a dedicated Diagnostic_Source.
Don't send the same diagnostics twice a row.
> U906-019 Introduce Diagnostic_Source interface

- source/ada/lsp-ada_documents.adb
- testsuite/ada_lsp/U915-024.completion.invisible_snippets/default.gpr
- testsuite/ada_lsp/U915-024.completion.invisible_snippets/main.adb
- testsuite/ada_lsp/U915-024.completion.invisible_snippets/test.ads
- testsuite/ada_lsp/U915-024.completion.invisible_snippets/test.json
- testsuite/ada_lsp/U915-024.completion.invisible_snippets/test.yaml
> U915-024: Don't insert 'invisible' in supbs snippets

- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-ada_handlers.ads
if didChangeConfiguration provides a different charset.
> U906-019 Don't skip project reloading

- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-ada_handlers.ads
Let ALS reload project on every configuration change
(if projectFile /= ""). This allows GS to reload project
on demand.
> U906-019 Revert project reloading optimization

- source/ada/lsp-ada_completions-parameters.adb
- source/ada/lsp-ada_completions-parameters.ads
- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-lal_utils.adb
- source/ada/lsp-lal_utils.ads
- testsuite/ada_lsp/U913-028.completion.params/default.gpr
- testsuite/ada_lsp/U913-028.completion.params/foo.adb
- testsuite/ada_lsp/U913-028.completion.params/test.json
- testsuite/ada_lsp/U913-028.completion.params/test.yaml
- testsuite/ada_lsp/completion.no_snippet_for_params/test.json
For a function call, propose a snippet with all parameters or
the parameters individually.
The choices are filtered using the previous designators.
Add a test.
> U913-028: Completion provider for parameters

- README.md
- integration/vscode/ada/package.json
- integration/vscode/ada/src/extension.ts
- integration/vscode/ada/src/gnatproveTaskProvider.ts
Update ada problem matcher regexp to accept more severities kinds.
> U218-014 Add task provider for gnatprove

- source/protocol/lsp-generic_notifications.adb
- source/protocol/lsp-generic_notifications.ads
Contains Token as a parameter for handlers that need it.
> T826-026 New Visit method has been added

- .github/workflows/build-binaries.sh
- .github/workflows/build-binaries.yml
and get rid of outdated GNAT CE 2020 for Mac OS
> U922-009 Use GCC 11 toolchain by alire

- source/tester/tester-tests.adb
- source/tester/tester-tests.ads
- testsuite/ada_lsp/README.md
- testsuite/ada_lsp/S314-015.refactor_change_parameter_mode_0/test.json
- testsuite/ada_lsp/S314-015.refactor_move_parameter_0/test.json
- testsuite/ada_lsp/S314-015.refactor_remove_parameter_0/test.json
- testsuite/ada_lsp/T318-086.suppress.separates.0/test.json
- testsuite/ada_lsp/U416-030.refactor_change_parameter_mode_0/test.json
- testsuite/ada_lsp/U416-030.refactor_remove_parameter_0/test.json
- testsuite/ada_lsp/U511-009.refactoring.import_with_use/test.json
- testsuite/ada_lsp/completion.invisible.runtime/test.json
by changing timeout logic. Reset timeout on each server message, so
while server sends messages within given timeout the tester
command keeps running.
> U617-025 Make test suite more stable

- .github/workflows/build-binaries.yml
> Switch GH Action CI to macos-10.15/ubuntu-18.04

- integration/vscode/ada/src/alsClientFeatures.ts
- integration/vscode/ada/src/extension.ts
- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-ada_handlers.ads
- source/protocol/generated/lsp-message_io.adb
- source/protocol/lsp-messages.ads
- source/protocol/lsp-types.ads
- source/tester/tester-tests.adb
- testsuite/ada_lsp/README.md
- testsuite/ada_lsp/refactoring_add_parameter/S314-015/test.yaml
- testsuite/ada_lsp/refactoring_add_parameter/UA25-015/default.gpr
- testsuite/ada_lsp/refactoring_add_parameter/UA25-015/main.adb
- testsuite/ada_lsp/refactoring_add_parameter/UA25-015/test.json
- testsuite/ada_lsp/refactoring_add_parameter/UA25-015/test.yaml
Cherry picked two commits from master.
> Fixes conflicts when merging master into edge

- source/ada/lsp-ada_documents.adb
- source/ada/lsp-ada_documents.ads
- source/ada/lsp-search-start_word_text.adb
This should fix stale_reference_error exceptions.
> UC13-013 Don't keep Libadalang's Defining_Name objects

- source/ada/lsp-ada_driver.adb
Use System_Environment for access to environment variables.
> V113-076 Use Standard_Paths to obtain home directory.

- source/ada/lsp-ada_completions-end_names.adb
- source/ada/lsp-ada_completions-end_names.ads
- source/ada/lsp-ada_handlers.adb
- testsuite/ada_lsp/completion.end_labels/test.json
- testsuite/ada_lsp/completion.end_labels2/test.json
as discussed live on the weekly meeting.
> U817-017 Drop `\n` in end name completion

- source/ada/lsp-ada_handlers.adb
- testsuite/ada_lsp/V201-024.goto.entry_and_asserts/default.gpr
- testsuite/ada_lsp/V201-024.goto.entry_and_asserts/foo.adb
- testsuite/ada_lsp/V201-024.goto.entry_and_asserts/test.json
- testsuite/ada_lsp/V201-024.goto.entry_and_asserts/test.yaml
Special case for "go to declaration" from an entry node to its
asserts nodes => show all the choices.
Add a test.
> V201-024: Implement goto from entry to asserts

- source/ada/lsp-ada_completions-aspects.adb
- testsuite/ada_lsp/completion.aspects/default.gpr
- testsuite/ada_lsp/completion.aspects/p.adb
- testsuite/ada_lsp/completion.aspects/test.json
- testsuite/ada_lsp/completion.aspects/test.yaml
> V223-010 Return all aspects in case of an empty

- Makefile
- source/gpr/lsp-gpr_handlers.adb
- testsuite/gpr_lsp/shutdown/shutdown.json
- testsuite/gpr_lsp/shutdown/test.yaml
on shutdown request. Add GPR LSP server test.
> Avoid Program_Error for GPR LSP server

- source/ada/lsp-ada_completions-names.adb
- source/ada/lsp-ada_handlers-invisibles.adb
This can happen when completion is trigerred while typing
within a comment for instance. Make sure to not try to complete
list of nodes, avoiding ALS hangs.
> V225-028: Don't try to complete Ada_Node_List nodes

- integration/vscode/ada/src/gnatproveTaskProvider.ts
Rename all GNATprove tasks to be "Prove xxx" like in GNAT Studio.
> UB26-005 Add tasks to Prove line/region

- .github/workflows/build-binaries.sh
- .github/workflows/build-binaries.yml
> Add templates-parser as a dependency.

- .github/workflows/build-binaries.sh
See 4731f58 commit in gpr repo or V420-024
> Fix libgpr2 building in GitHub Action CI.

- README.md
- integration/vscode/ada/src/gnatproveTaskProvider.ts
Use promises as getting all symbols returns a promise.
> UB26-005 Add task for proof of subprogram

- README.md
- integration/vscode/ada/src/gnatproveTaskProvider.ts
Complete the tasks associated to GNATprove, to have the same as in
GNAT Studio.
> UB26-005 Add Examine tasks for GNATprove flow analysis

- testsuite/ada_lsp/T318-086.suppress.separates.0/test.json
Same refactoring but with the correct indentation.
> V425-012 Update test baseline

- source/ada/lsp-ada_handlers.adb
This adds defensive programming in some cases where
Get_Open_Document is called and the result is expected
to be non-null. Traces these in the log and abandon the
request, rather than crashing with Constraint_Error.
> V516-040 Add defensive programming on Get_Open_Document

- source/ada/lsp-ada_completions-aggregates.adb
- testsuite/ada_lsp/completion.aggregates.snippet_indexes/default.gpr
- testsuite/ada_lsp/completion.aggregates.snippet_indexes/main.adb
- testsuite/ada_lsp/completion.aggregates.snippet_indexes/test.json
- testsuite/ada_lsp/completion.aggregates.snippet_indexes/test.yaml
And add an automatic test for this.
> V223-056: Fix aggregate snippet indexes generation

- doc/settings.md
- integration/vscode/ada/package.json
- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-ada_handlers.ads
And an associated VS Code preference, disabled by default.
> V609-058: Add useCompletionSnippets flag

- .github/workflows/build-binaries.sh
- .github/workflows/build-binaries.yml
- Makefile
- README.md
- gnat/lsp_server.gpr
This reverts commit 5f888a060de8ae411231bd7a347a189665240677.
> Revert "UC15-036 Add `gpr-unit-provider` dependency"

- source/ada/lsp-ada_driver.adb
- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-ada_handlers.ads
Add logThreshold property to limit the number of logs.
> V704-034: Limit number of logs in $ALS_HOME/.als

- source/ada/lsp-ada_handlers-file_readers.adb
- source/ada/lsp-ada_handlers-file_readers.ads
- source/ada/lsp-ada_handlers.adb
- testsuite/ada_lsp/preprocessor/p.gpr
> V315-025: Use new LAL's API for preprocessing

- .github/workflows/build-binaries.yml
> Set the GHA builder to use gcc-12

- source/ada/lsp-ada_completions-parameters.adb
- testsuite/ada_lsp/completion.param.non_basic_calls/default.gpr
- testsuite/ada_lsp/completion.param.non_basic_calls/foo.adb
- testsuite/ada_lsp/completion.param.non_basic_calls/test.json
- testsuite/ada_lsp/completion.param.non_basic_calls/test.yaml
> V804-025: Param completion for non_basic_decl

- integration/vscode/ada/src/extension.ts
Use the already existing VS Code preferences to control
the environment variables and pass them to all the child
processes launched by the extension, including the ALS.
This allows to set a custom PATH or GPR_PROJECT_PATH in a
workspace file for a given project for instance, or control
the scenario variables directly from the environment.
> V119-052: pass custom env variables to the ALS

- integration/vscode/Code Samples/custom_env/README.md
- integration/vscode/Code Samples/custom_env/custom_env.code-workspace
- integration/vscode/Code Samples/custom_env/default.gpr
- integration/vscode/Code Samples/custom_env/imported/print.adb
- integration/vscode/Code Samples/custom_env/imported/print_utils.gpr
- integration/vscode/Code Samples/custom_env/src/main_2.adb
- source/ada/lsp-ada_driver.adb
This shows an example of VS Code workspace that modifies some environment variables at startup.
> V119-052: Add a code sample for custom environments

- source/client/lsp-raw_clients.adb
It was detected when GNATpp was sending message in stdout polluting the json stream and making the raw_client do an infinite loop (it was never consuming the "invalid json")
=> implement a basic defensive mechanism consuming the lines one by one until finding a proper json header
> VA05-011: Make lsp_client resilient to invalid json

- source/ada/lsp-ada_highlighters.adb
- testsuite/ada_lsp/V628-012.highlighting.no-libs/foo.adb
- testsuite/ada_lsp/V628-012.highlighting.no-libs/test.json
- testsuite/ada_lsp/V628-012.highlighting.no-libs/test.yaml
to avoid returning token types/modifiers not supported by the client and avoid raising CONSTRAINT_ERROR.
Fixes #1070
> Fix semanticTokens request

- source/ada/lsp-ada_completions.adb
- testsuite/ada_lsp/completion.snippet.formatting/test.json
- testsuite/ada_lsp/completion.snippet.formatting2/test.json
- testsuite/ada_lsp/completion.snippet.formatting3/test.json
Also set filterText to prevent clients from hiding snippet (VS code for example).
> VA28-021: Activate snippet formatting by default

- source/ada/lsp-ada_completions.adb
- source/ada/lsp-ada_documents.adb
- source/ada/lsp-ada_documents.ads
- testsuite/ada_lsp/T527-019.range_formatting/test.json
- testsuite/ada_lsp/range_formatting/UB30-006_range_format_whole_document/test.json
Support partial formatting of Ada_List slices.
Update tests baseline.
> VB10-040 Adjust to latest gnatpp partial formatting API

- testsuite/ada_lsp/T713-012.completion.generic_package/test.json
- testsuite/ada_lsp/V628-024.symbol_diff/test.json
- testsuite/ada_lsp/completion.snippet.formatting/test.json
- testsuite/ada_lsp/completion.snippet.formatting2/test.json
- testsuite/ada_lsp/completion.snippet.formatting3/test.json
- testsuite/ada_lsp/incorrect_fallback/incorrect_fallback.json
Several tests have incorrect/misplaced `wait` clauses. Fix them.
> Fix some tests.

- source/ada/lsp-ada_completions-filters.adb
- source/ada/lsp-ada_completions-filters.ads
- source/ada/lsp-ada_completions-pragmas.adb
- source/ada/lsp-ada_completions-use_clauses.adb
- source/ada/lsp-ada_completions-use_clauses.ads
- source/ada/lsp-ada_documents.adb
- source/ada/lsp-ada_handlers.adb
- testsuite/ada_lsp/completion.use_clauses.multiple_with/default.gpr
- testsuite/ada_lsp/completion.use_clauses.multiple_with/main.adb
- testsuite/ada_lsp/completion.use_clauses.multiple_with/test.json
- testsuite/ada_lsp/completion.use_clauses.multiple_with/test.yaml
- testsuite/ada_lsp/completion.use_clauses/default.gpr
- testsuite/ada_lsp/completion.use_clauses/main.adb
- testsuite/ada_lsp/completion.use_clauses/test.json
- testsuite/ada_lsp/completion.use_clauses/test.yaml
This provider proposes the use-clause corresponding to the with-clause on the same line, if any.
> VC16-002: Add use-clause completion provider

- source/ada/lsp-ada_completions-generic_assoc.adb
- source/ada/lsp-ada_completions-generic_assoc.ads
- source/ada/lsp-ada_completions-parameters.adb
- source/ada/lsp-ada_completions-parameters.ads
- source/ada/lsp-ada_contexts.adb
- source/ada/lsp-ada_contexts.ads
- source/ada/lsp-ada_documents.adb
- source/ada/lsp-ada_documents.ads
- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-lal_utils.adb
- source/ada/lsp-lal_utils.ads
- testsuite/ada_lsp/signature.aggregate/default.gpr
- testsuite/ada_lsp/signature.aggregate/foo.adb
- testsuite/ada_lsp/signature.aggregate/test.json
- testsuite/ada_lsp/signature.aggregate/test.yaml
- testsuite/ada_lsp/signature.aggregate2/default.gpr
- testsuite/ada_lsp/signature.aggregate2/foo.adb
- testsuite/ada_lsp/signature.aggregate2/test.json
- testsuite/ada_lsp/signature.aggregate2/test.yaml
- testsuite/ada_lsp/signature.generic/default.gpr
- testsuite/ada_lsp/signature.generic/src/foo.adb
- testsuite/ada_lsp/signature.generic/src/g.ads
- testsuite/ada_lsp/signature.generic/src/inst.ads
- testsuite/ada_lsp/signature.generic/test.json
- testsuite/ada_lsp/signature.generic/test.yaml
Move signatureHelp logic in parameter completion.
Add test for signatureHelp and generic instantiation. 
Add tests for signatureHelp and aggregates.
> V901-009: Generate Signatures using the Parameter completion

- source/ada/lsp-ada_contexts.adb
- source/ada/lsp-ada_contexts.ads
- source/ada/lsp-ada_documents.adb
- source/ada/lsp-ada_documents.ads
- source/ada/lsp-ada_handlers.adb
- source/ada/lsp-lal_utils.adb
- source/ada/lsp-lal_utils.ads
- testsuite/ada_lsp/completion.invisible.runtime/test.json
- testsuite/ada_lsp/completion.invisible2/test.json
- testsuite/ada_lsp/completion.subp_parameters/test.json
Without logging the exception, which is too noisy. This code will be replaced by gnatdoc at some point.
> VB24-035: Add exception handler when computing doc

- doc/initialization.md
- doc/settings.md
- scripts/io_gen.py
- source/ada/lsp-ada_handlers.adb
- source/protocol/generated/lsp-message_io.adb
- source/protocol/lsp-messages.ads
- testsuite/ada_lsp/project_config.init/aaa.adb
- testsuite/ada_lsp/project_config.init/project_config.json
- testsuite/ada_lsp/project_config.init/right_project.gpr
- testsuite/ada_lsp/project_config.init/second.ads
- testsuite/ada_lsp/project_config.init/test.yaml
- testsuite/ada_lsp/project_config.init/third.ads
- testsuite/ada_lsp/project_config.init/wrong_project.gpr
from `initializationOptions` of `initialize` request.
> VB30-016 Read initial configuration

- integration/vscode/ada/ada-snippets.json
As mentioned in https://github.com/AdaCore/ada_language_server/issues/1080
> Expanded the case snippet in ada-snippets.json
